const fs = require('fs');

// BATCH 1: VOCABULARY (50 ITEMS)
const batch1 = [
  // Synonyms
  {"category":"Verbal Ability","prompt":"Choose the word that is MOST SIMILAR in meaning to the underlined word: The manager's CUMBERSOME procedures delayed the approval.","optionA":"A. Efficient","optionB":"B. Unwieldy","optionC":"C. Modern","optionD":"D. Swift","answerIndex":1,"explanation":"'Cumbersome' means heavy, clumsy, or unwieldy. Option B is correct."},
  {"category":"Verbal Ability","prompt":"Piliin ang salitang KAKASING-KAHULUGAN ng salitang may salungguhit: Ang kanyang tagumpay ay bunga ng kanyang MASIDHIng pagpapatsiyamba at pagsisikap.","optionA":"A. Mahina","optionB":"B. Matindi","optionC":"C. Mabagal","optionD":"D. Maimbot","answerIndex":1,"explanation":"Ang 'masidhi' ay nangangahulugang matindi o labis. Ang B ang tamang sagot."},
  {"category":"Verbal Ability","prompt":"Choose the word that is MOST SIMILAR in meaning to the underlined word: Her MENTOR provided invaluable career advice.","optionA":"A. Adviser","optionB":"B. Rival","optionC":"C. Student","optionD":"D. Opponent","answerIndex":0,"explanation":"A 'mentor' is an experienced counselor or adviser. Option A is correct."},
  {"category":"Verbal Ability","prompt":"Piliin ang salitang KAKASING-KAHULUGAN ng salitang may salungguhit: Naging MABISA ang bagong panukala sa pagpapababa ng krimen.","optionA":"A. Walang silbi","optionB":"B. Epektibo","optionC":"C. Mabagal","optionD":"D. Mapanganib","answerIndex":1,"explanation":"Ang 'mabisa' ay nangangahulugang epektibo. Ang B ang tamang sagot."},
  {"category":"Verbal Ability","prompt":"Choose the word that is MOST SIMILAR in meaning to the underlined word: The committee tried to MITIGATE the disaster's financial impact.","optionA":"A. Increase","optionB":"B. Lessen","optionC":"C. Ignore","optionD":"D. Prolong","answerIndex":1,"explanation":"'Mitigate' means to make less severe or lessen. Option B is correct."},
  {"category":"Verbal Ability","prompt":"Piliin ang salitang KAKASING-KAHULUGAN ng salitang may salungguhit: Sadyang WAGAS ang pagmamahal ng ina sa kanyang anak.","optionA":"A. Maling","optionB":"B. Dalisay","optionC":"C. Peke","optionD":"D. Pansamantala","answerIndex":1,"explanation":"Ang 'wagas' ay nangangahulugang dalisay o tapat. Ang B ang tamang sagot."},
  {"category":"Verbal Ability","prompt":"Choose the word that is MOST SIMILAR in meaning to the underlined word: His METICULOUS planning ensured zero technical failures.","optionA":"A. Careless","optionB":"B. Thorough","optionC":"C. Hasty","optionD":"D. Sloppy","answerIndex":1,"explanation":"'Meticulous' means showing extreme care and precision (thorough). Option B is correct."},
  {"category":"Verbal Ability","prompt":"Piliin ang salitang KAKASING-KAHULUGAN ng salitang may salungguhit: Ang pamahalaan ay nagbigay ng ANGKOP na tulong sa mga nasalanta.","optionA":"A. Strikto","optionB":"B. Nararapat","optionC":"C. Kulang","optionD":"D. Mabilis","answerIndex":1,"explanation":"Ang 'angkop' ay nangangahulugang nararapat o nababagay. Ang B ang tamang sagot."},
  {"category":"Verbal Ability","prompt":"Choose the word that is MOST SIMILAR in meaning to the underlined word: The CEO gave a CANDID assessment of company earnings.","optionA":"A. Deceptive","optionB":"B. Frank","optionC":"C. Vague","optionD":"D. Hesitant","answerIndex":1,"explanation":"'Candid' means truthful and straightforward (frank). Option B is correct."},
  {"category":"Verbal Ability","prompt":"Piliin ang salitang KAKASING-KAHULUGAN ng salitang may salungguhit: NAGALAK ang buong bayan sa pagkapanalo ng koponan.","optionA":"A. Nalungkot","optionB":"B. Natuwa","optionC":"C. Nagalit","optionD":"D. Natakot","answerIndex":1,"explanation":"Ang 'nagalak' ay nangangahulugang natuwa o nagalak. Ang B ang tamang sagot."},
  
  // Antonyms
  {"category":"Verbal Ability","prompt":"Choose the word that is MOST OPPOSITE in meaning to the underlined word: The court found the evidence to be IRRELEVANT.","optionA":"A. Pertinent","optionB":"B. Unrelated","optionC":"C. Trivial","optionD":"D. Foreign","answerIndex":0,"explanation":"'Irrelevant' means not applicable; its opposite is 'Pertinent' (relevant). Option A is correct."},
  {"category":"Verbal Ability","prompt":"Piliin ang SALUNGAT na kahulugan ng salitang may salungguhit: Ang kanyang mga pahayag ay DUKHA sa katotohanan.","optionA":"A. Mahirap","optionB":"B. Mayaman","optionC":"C. Kulang","optionD":"D. Kakaunti","answerIndex":1,"explanation":"Ang 'dukha' ay nangangahulugang mahirap; ang kasalungat nito ay 'mayaman'. Ang B ang tamang sagot."},
  {"category":"Verbal Ability","prompt":"Choose the word that is MOST OPPOSITE in meaning to the underlined word: Public response to the economic proposal was AMBIGUOUS.","optionA":"A. Vague","optionB":"B. Clear","optionC":"C. Obscure","optionD":"D. Uncertain","answerIndex":1,"explanation":"'Ambiguous' means unclear; its antonym is 'Clear'. Option B is correct."},
  {"category":"Verbal Ability","prompt":"Piliin ang SALUNGAT na kahulugan ng salitang may salungguhit: MASYADONG MATALAS ang kanyang dila sa pakikipag-usap.","optionA":"A. Matalas","optionB":"B. Mahinhin","optionC":"C. Matalim","optionD":"D. Masungit","answerIndex":1,"explanation":"Ang kasalungat ng 'matalas ang dila' (masakit magsalita) ay mahinhin o malumanay. Ang B ang tamang sagot."},
  {"category":"Verbal Ability","prompt":"Choose the word that is MOST OPPOSITE in meaning to the underlined word: She showed a DILIGENT effort in submitting all audit filings.","optionA":"A. Lazy","optionB":"B. Industrious","optionC":"C. Hardworking","optionD":"D. Focused","answerIndex":0,"explanation":"'Diligent' means hardworking; its opposite is 'Lazy'. Option A is correct."},
  {"category":"Verbal Ability","prompt":"Piliin ang SALUNGAT na kahulugan ng salitang may salungguhit: Ang lugar na iyon ay LIGTAS para sa mga turista.","optionA":"A. Payapa","optionB":"B. Mapanganib","optionC":"C. Malinis","optionD":"D. Tahimik","answerIndex":1,"explanation":"Ang kasalungat ng 'ligtas' ay 'mapanganib'. Ang B ang tamang sagot."},
  {"category":"Verbal Ability","prompt":"Choose the word that is MOST OPPOSITE in meaning to the underlined word: The country experienced an ABUNDANCE of crop yield.","optionA":"A. Surplus","optionB":"B. Scarcity","optionC":"C. Wealth","optionD":"D. Profusion","answerIndex":1,"explanation":"'Abundance' means plentiful supply; its opposite is 'Scarcity'. Option B is correct."},
  {"category":"Verbal Ability","prompt":"Piliin ang SALUNGAT na kahulugan ng salitang may salungguhit: TANTANAN mo na ang pangingialam sa buhay ng iba.","optionA":"A. Itigil","optionB":"B. Ipagpatuloy","optionC":"C. Magsimula","optionD":"D. Huwag pansinin","answerIndex":1,"explanation":"Ang 'tantanan' ay itigil; ang kasalungat nito ay 'ipagpatuloy'. Ang B ang tamang sagot."},
  {"category":"Verbal Ability","prompt":"Choose the word that is MOST OPPOSITE in meaning to the underlined word: The board reached a UNANIMOUS decision.","optionA":"A. Divided","optionB":"B. Complete","optionC":"C. Solid","optionD":"D. Harmonious","answerIndex":0,"explanation":"'Unanimous' means in complete agreement; its opposite is 'Divided'. Option A is correct."},
  {"category":"Verbal Ability","prompt":"Piliin ang SALUNGAT na kahulugan ng salitang may salungguhit: PUNO ng pag-asa ang kanyang dibdib habang naghihintay.","optionA":"A. Marami","optionB":"B. Sapat","optionC":"C. Salat","optionD":"D. Sobra","answerIndex":2,"explanation":"Ang kasalungat ng 'puno' (marami) sa kontekstong ito ay 'salat' (kulang/walan). Ang C ang tamang sagot."},

  // Word Meaning
  {"category":"Verbal Ability","prompt":"Which definition best fits the term 'BENEVOLENT'?","optionA":"A. Having a wish to do good to others","optionB":"B. Showing a hatred toward society","optionC":"C. Expressing severe legal judgment","optionD":"D. Acting with financial negligence","answerIndex":0,"explanation":"'Benevolent' means well-meaning and kindly. Option A is correct."},
  {"category":"Verbal Ability","prompt":"Ano ang tamang kahulugan ng salitang 'PANIPI' sa Balarilang Filipino?","optionA":"A. Bantas na ginagamit sa pagpipitas ng salita (' ' o \" \")","optionB":"B. Isang uri ng pang-uri","optionC":"C. Bahagi ng pandiwa","optionD":"D. Uri ng pangatnig","answerIndex":0,"explanation":"Ang 'panipi' (quotation marks) ay isang uri ng bantas sa pagsulat. Ang A ang tamang sagot."},
  {"category":"Verbal Ability","prompt":"What is the precise meaning of 'PRAGMATIC'?","optionA":"A. Guided by abstract idealism","optionB":"B. Dealing with matters sensibly and practically","optionC":"C. Focused strictly on ancient history","optionD":"D. Highly reckless in decision making","answerIndex":1,"explanation":"'Pragmatic' means practical and realistic. Option B is correct."},
  {"category":"Verbal Ability","prompt":"Ano ang ibig sabihin ng salitang 'TALATINIGAN'?","optionA":"A. Aklat ng mga mapa","optionB":"B. Diksyunaryo","optionC":"C. Aklat ng mga kasaysayan","optionD":"D. Panuntunan sa batas","answerIndex":1,"explanation":"Ang 'talatinigan' ay ang katutubong tawag sa diksyunaryo. Ang B ang tamang sagot."},
  {"category":"Verbal Ability","prompt":"What does 'EPHEMERAL' mean?","optionA":"A. Permanent and everlasting","optionB":"B. Lasting for a very short time","optionC":"C. Deeply religious","optionD":"D. Financially burdensome","answerIndex":1,"explanation":"'Ephemeral' means transitory or lasting for a short time. Option B is correct."},
  {"category":"Verbal Ability","prompt":"Ano ang ibig sabihin ng salitang 'SULATRONIKO'?","optionA":"A. Liham sa koreo","optionB":"B. Email","optionC":"C. Telepono","optionD":"D. Pahayagan","answerIndex":1,"explanation":"Ang 'sulatroniko' ay ang katumbas ng 'electronic mail' o email sa Filipino. Ang B ang tamang sagot."},
  {"category":"Verbal Ability","prompt":"What is the definition of 'UBIQUITOUS'?","optionA":"A. Rare and difficult to find","optionB":"B. Present, appearing, or found everywhere","optionC":"C. Dangerous to public health","optionD":"D. Related to legal prosecution","answerIndex":1,"explanation":"'Ubiquitous' means present everywhere simultaneously. Option B is correct."},
  {"category":"Verbal Ability","prompt":"Ano ang kahulugan ng 'LIPUNAN'?","optionA":"A. Pangkat ng mga taong nabubuhay sa isang pamayanan","optionB":"B. Isang uri ng hayop","optionC":"C. Gusali ng pamahalaan","optionD":"D. Batas ng kalikasan","answerIndex":0,"explanation":"Ang 'lipunan' ay pangkat ng mga taong nagkakasundo sa mga layunin sa buhay. Ang A ang tamang sagot."},
  {"category":"Verbal Ability","prompt":"Which word refers to 'a formal statement of resignation or surrender'?","optionA":"A. Abdication","optionB":"B. Adoption","optionC":"C. Accolade","optionD":"D. Aggravation","answerIndex":0,"explanation":"'Abdication' is the formal renunciation or surrender of a duty or throne. Option A is correct."},
  {"category":"Verbal Ability","prompt":"Ano ang kahulugan ng salitang 'BARTOLINA'?","optionA":"A. Silid-aklatan","optionB":"B. Kulungan o bilangguan","optionC":"C. Hukuman","optionD":"D. Ospital","answerIndex":1,"explanation":"Ang 'bartolina' ay tumutukoy sa silid-kulungan o bilangguan. Ang B ang tamang sagot."},

  // Context Clues
  {"category":"Verbal Ability","prompt":"Based on the sentence context, infer the meaning of the underlined word: Unlike her VIVACIOUS sister who loves parties, Karen is quiet and introverted.","optionA":"A. Lively and animated","optionB":"B. Sad and depressed","optionC":"C. Dishonest","optionD":"D. Weak","answerIndex":0,"explanation":"The contrast ('Unlike her... Karen is quiet') indicates 'vivacious' means lively and energetic. Option A is correct."},
  {"category":"Verbal Ability","prompt":"Gamitin ang pahiwatig ng pangungusap: Dahil sa kanyang KASAPAKATAN, nahuli rin ng mga pulis ang utak sa pagnanakaw.","optionA":"A. Kasama sa masamang balak","optionB":"B. Kaaway","optionC":"C. Tagapagtanggol","optionD":"D. Biktima","answerIndex":0,"explanation":"Ang 'kasapakatan' ay nangangahulugang kasabwat o kasama sa masamang balak. Ang A ang tamang sagot."},
  {"category":"Verbal Ability","prompt":"Infer the meaning using context clues: The salary was MEAGER, barely enough to pay for rent and basic food.","optionA":"A. Abundant","optionB":"B. Small or inadequate","optionC":"C. Excessive","optionD":"D. Generous","answerIndex":1,"explanation":"'Barely enough to pay for rent' indicates 'meager' means small or inadequate. Option B is correct."},
  {"category":"Verbal Ability","prompt":"Gamitin ang pahiwatig ng pangungusap: Mabilis siyang PUMANAW matapos ang matagal na pakikipaglaban sa malubhang karamdaman.","optionA":"A. Gumaling","optionB":"B. Namatay","optionC":"C. Umalis","optionD":"D. Naglakbay","answerIndex":1,"explanation":"Ang 'pumanaw' sa kontekstong ito ay nangangahulugang namatay. Ang B ang tamang sagot."},
  {"category":"Verbal Ability","prompt":"Infer the meaning: The NOVICE driver accidentally stepped on the gas instead of the brakes.","optionA":"A. Professional","optionB":"B. Beginner","optionC":"C. Veteran","optionD":"D. Expert","answerIndex":1,"explanation":"Accidentally stepping on the wrong pedal implies a beginner or inexperienced driver ('novice'). Option B is correct."},
  {"category":"Verbal Ability","prompt":"Gamitin ang pahiwatig ng pangungusap: Naging HANTUNGAN ng kanyang pagsisikap ang mataas na posisyon sa kumpanya.","optionA":"A. Simula","optionB":"B. Katapusan o Bunga","optionC":"C. Hadlang","optionD":"D. Dahilan","answerIndex":1,"explanation":"Ang 'hantungan' ay ang kinahinatnan, bunga, o dulo ng pagsisikap. Ang B ang tamang sagot."},
  {"category":"Verbal Ability","prompt":"Infer the meaning: The diplomat's TACTFUL response satisfied both disagreeing parties without causing offense.","optionA":"A. Rude","optionB":"B. Diplomatic and thoughtful","optionC":"C. Aggressive","optionD":"D. Careless","answerIndex":1,"explanation":"Satisfying both parties without offense shows a 'tactful' (thoughtful) approach. Option B is correct."},
  {"category":"Verbal Ability","prompt":"Gamitin ang pahiwatig ng pangungusap: Huwag kang MAG-ATUBILI na humingi ng tulong kung kailangan mo.","optionA":"A. Magmadali","optionB":"B. Mag-alinlangan","optionC":"C. Magalit","optionD":"D. Magyabang","answerIndex":1,"explanation":"Ang 'mag-atubili' ay nangangahulugang mag-alinlangan o magdalawang-isip. Ang B ang tamang sagot."},
  {"category":"Verbal Ability","prompt":"Infer the meaning: The ARDUOUS climb up Mount Apo exhausted even the experienced mountaineers.","optionA":"A. Easy","optionB":"B. Difficult and tiring","optionC":"C. Short","optionD":"D. Enjoyable","answerIndex":1,"explanation":"An action that exhausts experienced climbers is 'arduous' (difficult/tiring). Option B is correct."},
  {"category":"Verbal Ability","prompt":"Gamitin ang pahiwatig ng pangungusap: Ang KAGANDAHANG-LOOB ng pamilya ay hindi nila malilimutan kailanman.","optionA":"A. Kabutihan","optionB":"B. Yabang","optionC":"C. Galit","optionD":"D. Pagmamataas","answerIndex":0,"explanation":"Ang 'kagandahang-loob' ay tumutukoy sa kabutihan o kabutihang-asal. Ang A ang tamang sagot."},

  // Idioms / Sawikain
  {"category":"Verbal Ability","prompt":"What does the English idiom 'TO BITE THE BULLET' mean?","optionA":"A. To act carelessly","optionB":"B. To face a painful or difficult situation bravely","optionC":"C. To start a physical fight","optionD":"D. To surrender immediately","answerIndex":1,"explanation":"'Bite the bullet' means facing an inevitable difficult situation with fortitude. Option B is correct."},
  {"category":"Verbal Ability","prompt":"Ano ang kahulugan ng sawikain na 'BALAT-SIBUYAS'?","optionA":"A. Sensitibo o madaling umiyak","optionB":"B. Matapang","optionC":"C. Masipag magluto","optionD":"D. Madaling magalit","answerIndex":0,"explanation":"Ang 'balat-sibuyas' ay nangangahulugang maramdamin o sobrang sensitibo. Ang A ang tamang sagot."},
  {"category":"Verbal Ability","prompt":"What does the idiom 'TO BURN THE MIDNIGHT OIL' mean?","optionA":"A. To waste electrical resources","optionB":"B. To study or work late into the night","optionC":"C. To set something on fire accidentally","optionD":"D. To wake up early in the morning","answerIndex":1,"explanation":"'Burn the midnight oil' means working late at night. Option B is correct."},
  {"category":"Verbal Ability","prompt":"Ano ang kahulugan ng sawikain na 'NAGBUBUHAT NG SARILING BANGKO'?","optionA":"A. Masipag mag-ehersisyo","optionB":"B. Nagmamayabang sa sariling kakayahan","optionC":"C. Nagtatrabaho sa karpintero","optionD":"D. Naghihirap sa buhay","answerIndex":1,"explanation":"Ang 'nagbubuhat ng sariling bangko' ay nagmamayabang sa sariling kakayahan. Ang B ang tamang sagot."},
  {"category":"Verbal Ability","prompt":"What does the idiom 'TAKE IT WITH A GRAIN OF SALT' mean?","optionA":"A. To add seasoning to food","optionB":"B. To view a statement with skepticism","optionC":"C. To accept news as absolute truth","optionD":"D. To become bitter toward someone","answerIndex":1,"explanation":"'Take with a grain of salt' means not taking something as completely accurate. Option B is correct."},
  {"category":"Verbal Ability","prompt":"Ano ang kahulugan ng sawikain na 'NAGBIBILANG NG POSTE'?","optionA":"A. Mabilis tumakbo","optionB":"B. Walang trabaho o naghahanap ng trabaho","optionC":"C. Inhenyero sa kuryente","optionD":"D. Matipid sa pera","answerIndex":1,"explanation":"Ang 'nagbibilang ng poste' ay nangangahulugang walang trabaho. Ang B ang tamang sagot."},
  {"category":"Verbal Ability","prompt":"What does the idiom 'BEATING AROUND THE BUSH' mean?","optionA":"A. Avoiding the main topic","optionB":"B. Cleaning the garden","optionC":"C. Speaking clearly and directly","optionD":"D. Searching for wild animals","answerIndex":0,"explanation":"'Beating around the bush' means speaking evasively without addressing the main point. Option A is correct."},
  {"category":"Verbal Ability","prompt":"Ano ang kahulugan ng sawikain na 'KAPIT-TUKO'?","optionA":"A. Mahigpit ang hawak o ayaw umalis sa posisyon","optionB":"B. Takot sa kulisap","optionC":"C. Mabait na kaibigan","optionD":"D. Mahusay mag-akyat","answerIndex":0,"explanation":"Ang 'kapit-tuko' ay nangangahulugang ayaw bumitiw sa hawak o tungkulin. Ang A ang tamang sagot."},
  {"category":"Verbal Ability","prompt":"What does the idiom 'ON THE FENCE' mean?","optionA":"A. Physical trespass","optionB":"B. Undecided or neutral between choices","optionC":"C. Highly enthusiastic","optionD":"D. In immediate financial ruin","answerIndex":1,"explanation":"Being 'on the fence' means remaining undecided. Option B is correct."},
  {"category":"Verbal Ability","prompt":"Ano ang kahulugan ng sawikain na 'ILAW NG TAHANAN'?","optionA":"A. Kuryente","optionB":"B. Ina o Nanay","optionC":"C. Ama o Tatay","optionD":"D. Panganay na anak","answerIndex":1,"explanation":"Ang 'ilaw ng tahanan' ay ang ina sa pamilya. Ang B ang tamang sagot."}
];

// BATCH 2: GRAMMAR (50 ITEMS)
const batch2 = [
  {"category":"Verbal Ability","prompt":"Neither the team leader nor the members _____ ready for the surprise audit.","optionA":"A. was","optionB":"B. were","optionC":"C. is","optionD":"D. has been","answerIndex":1,"explanation":"With 'neither... nor', the verb agrees with the closer subject ('members', plural). 'Were' is correct."},
  {"category":"Verbal Ability","prompt":"Either the director or her assistants _____ responsible for updating the project schedule.","optionA":"A. are","optionB":"B. is","optionC":"C. was","optionD":"D. has been","answerIndex":0,"explanation":"With 'either... or', the verb agrees with the nearer subject ('assistants', plural). 'Are' is correct."},
  {"category":"Verbal Ability","prompt":"Each of the new applicants _____ required to submit a verified NBI clearance.","optionA":"A. are","optionB":"B. is","optionC":"C. have","optionD":"D. were","answerIndex":1,"explanation":"'Each' is an indefinite singular pronoun requiring a singular verb ('is')."},
  {"category":"Verbal Ability","prompt":"The board of directors _____ meeting in the executive lounge today.","optionA":"A. is","optionB":"B. are","optionC":"C. have been","optionD":"D. were","answerIndex":0,"explanation":"Collective nouns acting as a single entity take singular verbs ('is')."},
  {"category":"Verbal Ability","prompt":"Ten thousand pesos _____ the total registration fee for the national conference.","optionA":"A. are","optionB":"B. is","optionC":"C. were","optionD":"D. have been","answerIndex":1,"explanation":"Amounts of money considered as a single total take a singular verb ('is')."},
  {"category":"Verbal Ability","prompt":"She is one of those officers who _____ always punctual for briefings.","optionA":"A. is","optionB":"B. are","optionC":"C. was","optionD":"D. has been","answerIndex":1,"explanation":"In 'one of those [plural noun] who...', 'who' refers to 'officers' (plural), so 'are' is correct."},
  {"category":"Verbal Ability","prompt":"Ang mag-asawang Santos ay _____ ng maayos na buhay para sa kanilang mga anak.","optionA":"A. nagsumikap","optionB":"B. nagsikap","optionC":"C. nagpapakasipag","optionD":"D. nagtataguyod","answerIndex":3,"explanation":"Ang pandiwang 'nagtataguyod' ay akmang ginagamit sa pagsasaad ng kasalukuyang gawaing pampamilya."},
  {"category":"Verbal Ability","prompt":"Bawat isa sa mga kawani ay _____ ng sariling pagkakakilanlan (ID).","optionA":"A. mayroon","optionB":"B. may","optionC":"C. meron","optionD":"D. magkaroon","answerIndex":1,"explanation":"Ang 'may' ay ginagamit kapag ang kasunod na salita ay pangngalan ('sariling pagkakakilanlan')."},
  {"category":"Verbal Ability","prompt":"The manager, accompanied by his deputies, _____ attending the regional forum.","optionA":"A. are","optionB":"B. is","optionC":"C. were","optionD":"D. have been","answerIndex":1,"explanation":"Intervening phrases ('accompanied by') do not alter the singular subject ('The manager'). 'Is' is correct."},
  {"category":"Verbal Ability","prompt":"Neither of the two proposed solutions _____ feasible under current budget limits.","optionA":"A. appear","optionB":"B. appears","optionC":"C. are appearing","optionD":"D. have appeared","answerIndex":1,"explanation":"'Neither' as a singular pronoun takes a singular verb ('appears')."},
  {"category":"Verbal Ability","prompt":"By the time the auditor arrives tomorrow, we _____ all financial records.","optionA":"A. will finish","optionB":"B. will have finished","optionC":"C. finished","optionD":"D. have finished","answerIndex":1,"explanation":"Future perfect tense ('will have finished') expresses an action completed before a future time point."},
  {"category":"Verbal Ability","prompt":"Si Maria ay _____ sa Maynila noong nakaraang taon.","optionA":"A. nag-aaral","optionB":"B. nag-aral","optionC":"C. mag-aaral","optionD":"D. nag-aaral pa","answerIndex":1,"explanation":"Ang 'noong nakaraang taon' ay tumutukoy sa nakalipas na kilos (naganap), kaya 'nag-aral' ang tama."},
  {"category":"Verbal Ability","prompt":"Scarcely had the speaker sat down when the audience _____ cheering.","optionA":"A. begins","optionB":"B. began","optionC":"C. will begin","optionD":"D. had begun","answerIndex":1,"explanation":"Past sequence of events requires past tense 'began' in the subordinate clause."},
  {"category":"Verbal Ability","prompt":"The agency _____ public advisories since early this morning.","optionA":"A. issued","optionB":"B. has been issuing","optionC":"C. is issuing","optionD":"D. will issue","answerIndex":1,"explanation":"Present perfect continuous ('has been issuing') indicates an action starting in the past and continuing up to the present."},
  {"category":"Verbal Ability","prompt":"_____ na si Juan nang dumating ang kanyang mga bisita.","optionA":"A. Kumakain","optionB":"B. Kumain","optionC":"C. Kakain","optionD":"D. Nakakain","answerIndex":1,"explanation":"Ang pangyayaring natapos na bago ang isa pang pangyayari sa nakaraan ay gumagamit ng 'Kumain'."},
  {"category":"Verbal Ability","prompt":"If I _____ the president of the organization, I would revise the bylaws immediately.","optionA":"A. am","optionB":"B. was","optionC":"C. were","optionD":"D. have been","answerIndex":2,"explanation":"Subjunctive conditional clauses expressing hypothetical situations use 'were'."},
  {"category":"Verbal Ability","prompt":"Bukas ng umaga ay _____ ang pangkalahatang pagpupulong sa Bulwagan.","optionA":"A. gaganapin","optionB":"B. ginanap","optionC":"C. ginaganap","optionD":"D. gaganap","answerIndex":0,"explanation":"Ang 'bukas ng umaga' ay nagpapahiwatig ng hinaharap (magaganap pa lamang), kaya 'gaganapin' ang tama."},
  {"category":"Verbal Ability","prompt":"They _____ in this municipality for over twenty years before relocating.","optionA":"A. live","optionB":"B. had lived","optionC":"C. have lived","optionD":"D. will live","answerIndex":1,"explanation":"Past perfect ('had lived') denotes an action completed before another past event."},
  {"category":"Verbal Ability","prompt":"Between you and _____, the new policy requires significant clarification.","optionA":"A. I","optionB":"B. me","optionC":"C. myself","optionD":"D. mine","answerIndex":1,"explanation":"Prepositions like 'between' govern objective pronoun forms ('you and me')."},
  {"category":"Verbal Ability","prompt":"Ang mga kagamitang ito ay para sa _____, kaya pakaingatan mo.","optionA":"A. iyo","optionB":"B. akin","optionC":"C. kaniya","optionD":"D. kanila","answerIndex":0,"explanation":"Ang 'iyo' ay ikalawang panauhan ng panghalip na paari na tumutukoy sa kausap."},
  {"category":"Verbal Ability","prompt":"The award was given to the committee member _____ achieved the highest rating.","optionA":"A. whom","optionB":"B. who","optionC":"C. whose","optionD":"D. which","answerIndex":1,"explanation":"'Who' acts as the subject of the clause 'achieved the highest rating'."},
  {"category":"Verbal Ability","prompt":"Siya ang lalaking _____ kotse ay nabangga sa kanto.","optionA":"A. na","optionB":"B. na ang","optionC":"C. kanino","optionD":"D. na kung saan","answerIndex":1,"explanation":"Sa pagsasaad ng pagmamay-ari o ugnayan sa Filipino, ginagamit ang 'na ang'."},
  {"category":"Verbal Ability","prompt":"Neither John nor Peter submitted _____ expense liquidation form on time.","optionA":"A. their","optionB":"B. his","optionC":"C. its","optionD":"D. our","answerIndex":1,"explanation":"Singular antecedents joined by 'neither... nor' take singular possessive pronouns ('his')."},
  {"category":"Verbal Ability","prompt":"Ibinigay ni G. Santos sa _____ ang mga opisyal na dokumento.","optionA":"A. amin","optionB":"B. kami","optionC":"C. ako","optionD":"D. ko","answerIndex":0,"explanation":"Ang 'amin' ay panghalip na paukol na ginagamit pagkatapos ng ukol na 'sa'."},
  {"category":"Verbal Ability","prompt":"Give the file to _____ requests it first.","optionA":"A. whoever","optionB":"B. whomever","optionC":"C. whom","optionD":"D. whichever","answerIndex":0,"explanation":"'Whoever' functions as the subject of the noun clause 'whoever requests it first'."},
  {"category":"Verbal Ability","prompt":"Sila _____ ang mga kinatawan ng ating lalawigan sa pambansang paligsahan.","optionA":"A. mismo","optionB":"B. din","optionC":"C. rin","optionD":"D. man","answerIndex":0,"explanation":"Ang 'mismo' ay ginagamit para sa pagbibigay ng diin sa panghalip na 'sila'."},
  {"category":"Verbal Ability","prompt":"The new guidelines are applicable _____ all government offices nationwide.","optionA":"A. with","optionB":"B. to","optionC":"C. on","optionD":"D. for","answerIndex":1,"explanation":"'Applicable' is followed idiomatically by the preposition 'to'."},
  {"category":"Verbal Ability","prompt":"Naglakbay sila _____ Maynila hanggang Baguio gamit ang bus.","optionA":"A. mula","optionB":"B. tungkol","optionC":"C. ayon","optionD":"D. laban","answerIndex":0,"explanation":"Ang 'mula' ay ginagamit sa pagsasaad ng pinagmulan ng paglalakbay."},
  {"category":"Verbal Ability","prompt":"She prefers working independently _____ working in large groups.","optionA":"A. than","optionB":"B. to","optionC":"C. over","optionD":"D. from","answerIndex":1,"explanation":"'Prefer' takes the preposition 'to' when comparing preferences."},
  {"category":"Verbal Ability","prompt":"Ayon _____ Batas Republika 6713, ang mga kawani ay dapat maging tapat sa bayan.","optionA":"A. sa","optionB":"B. kay","optionC":"C. para","optionD":"D. ukol","answerIndex":0,"explanation":"Ang 'Ayon sa' ay ginagamit kapag ang kasunod ay pangkalahatang pangngalan tulad ng 'Batas'."},
  {"category":"Verbal Ability","prompt":"The official expressed his compliance _____ the court mandate.","optionA":"A. with","optionB":"B. to","optionC":"C. in","optionD":"D. on","answerIndex":0,"explanation":"'Compliance' is idiomatically followed by 'with'."},
  {"category":"Verbal Ability","prompt":"Ang talakayan ay nakatuon _____ mga bagong probisyon ng Saligang Batas.","optionA":"A. sa mga","optionB":"B. kay","optionC":"C. para kay","optionD":"D. ukol kay","answerIndex":0,"explanation":"Ang 'sa mga' ay tamang pang-ukol para sa maramihang pangngalan ('mga bagong probisyon')."},
  {"category":"Verbal Ability","prompt":"He was proficient _____ both oral and written communication skills.","optionA":"A. at","optionB":"B. in","optionC":"C. with","optionD":"D. on","answerIndex":1,"explanation":"'Proficient' is idiomatically followed by 'in' when referring to skills."},
  {"category":"Verbal Ability","prompt":"Ang relief goods ay nakalaan _____ mga biktima ng baha.","optionA":"A. para sa","optionB":"B. ukol kay","optionC":"C. ayon sa","optionD":"D. laban sa","answerIndex":0,"explanation":"Ang 'para sa' ay ginagamit sa pagsasaad ng pinag-uukulan ng isang bagay."},
  {"category":"Verbal Ability","prompt":"Despite the heavy rain, _____ the team proceeded with the outdoor survey.","optionA":"A. but","optionB":"B. yet","optionC":"C. omitting 'yet/but' is required","optionD":"D. and","answerIndex":2,"explanation":"'Despite' introduces a prepositional phrase; adding 'but/yet' creates redundancy. Option C is correct."},
  {"category":"Verbal Ability","prompt":"Mabilis siyang tumakbo _____ nahuli pa rin siya sa huling biyahe ng tren.","optionA":"A. subalit","optionB":"B. dahil","optionC":"C. upang","optionD":"D. kaya","answerIndex":0,"explanation":"Ang 'subalit' ay pangatnig na paninsay (nagpapakita ng pagsasalungat)."},
  {"category":"Verbal Ability","prompt":"Not only did he complete the audit, _____ he also formulated new safety protocols.","optionA":"A. but","optionB":"B. but also","optionC":"C. and","optionD":"D. or","answerIndex":1,"explanation":"'Not only... but also' is a correlative conjunction pair."},
  {"category":"Verbal Ability","prompt":"Mag-aral kang mabuti _____ makapasa ka sa Exam ng Civil Service.","optionA":"A. upang","optionB":"B. samantalang","optionC":"C. kaysa","optionD":"D. maging","answerIndex":0,"explanation":"Ang 'upang' ay pangatnig na pananhi/panlayon (nagsasaad ng layunin)."},
  {"category":"Verbal Ability","prompt":"You must submit the document today; _____, your application will be cancelled.","optionA":"A. otherwise","optionB":"B. therefore","optionC":"C. furthermore","optionD":"D. moreover","answerIndex":0,"explanation":"'Otherwise' expresses the consequence of failing to fulfill the condition."},
  {"category":"Verbal Ability","prompt":"Nagsikap siya nang maigi _____ hindi pa rin sapat ang kanyang naipon.","optionA":"A. palibhasa","optionB":"B. datapwat","optionC":"C. kaya","optionD":"D. dahil","answerIndex":1,"explanation":"Ang 'datapwat' ay nangangahulugang subalit o ngunit (paninsay)."},
  {"category":"Verbal Ability","prompt":"Choose the sentence with correct capitalization and punctuation.","optionA":"A. The President of the Philippines delivered his State of the Nation Address.","optionB":"B. the President of the philippines delivered his state of the nation address.","optionC":"C. The president of the Philippines delivered His state of the nation address.","optionD":"D. The President Of The Philippines delivered his state of the nation address.","answerIndex":0,"explanation":"Official titles preceding names or referring to specific heads of state are capitalized."},
  {"category":"Verbal Ability","prompt":"Alin sa mga sumusunod ang may TAMAng gamit ng gitling (-)?","optionA":"A. mag-aral","optionB":"B. mag-aaral","optionC":"C. pag-asa","optionD":"D. Lahat ng nabanggit","answerIndex":3,"explanation":"Lahat ng nabanggit ay tama sa paggamit ng gitling."},
  {"category":"Verbal Ability","prompt":"Which of the following uses articles correctly?","optionA":"A. An European expert arrived at a university today.","optionB":"B. A European expert arrived at a university today.","optionC":"C. An European expert arrived at an university today.","optionD":"D. A European expert arrived at an university today.","answerIndex":1,"explanation":"'European' and 'University' both start with a consonant sound (/j/), requiring 'A'."},
  {"category":"Verbal Ability","prompt":"Aling pangungusap ang may TAMAng bantas?","optionA":"A. 'Kailan gaganapin ang pagsusulit?' tanong ni Pedro.","optionB":"B. Kailan gaganapin ang pagsusulit, tanong ni Pedro?","optionC":"C. 'Kailan gaganapin ang pagsusulit!' tanong ni Pedro.","optionD":"D. Kailan gaganapin ang pagsusulit? tanong ni Pedro","answerIndex":0,"explanation":"Ang direktang tanong sa loob ng panipi ay nagtatapos sa tandang pananong bago ang panipi."},
  {"category":"Verbal Ability","prompt":"Which sentence demonstrates proper use of the semicolon (;)?","optionA":"A. The report was lengthy; however, it contained critical insights.","optionB":"B. The report was lengthy; and contained critical insights.","optionC":"C. The report was lengthy, however; it contained critical insights.","optionD":"D. The report was lengthy; however it contained critical insights.","answerIndex":0,"explanation":"A semicolon precedes conjunctive adverbs ('however') joining independent clauses."},
  {"category":"Verbal Ability","prompt":"Alin sa mga sumusunod na salita ang TAMA ang pagkakabaybay sa Wikang Filipino?","optionA":"A. nakapagtataka","optionB":"B. nakakapagtataka","optionC":"C. nakapagtatataka","optionD":"D. nakakapagtatataka","answerIndex":0,"explanation":"Ayon sa Balarila, ang wastong porma ay 'nakapagtataka'."},
  {"category":"Verbal Ability","prompt":"Select the option with correct punctuation for a series.","optionA":"A. We bought paper, pens, and folders.","optionB":"B. We bought paper, pens and folders.","optionC":"C. We bought paper pens and folders.","optionD":"D. We bought, paper, pens, and folders.","answerIndex":0,"explanation":"The Oxford comma before 'and' in a list is standard in formal exam writing."},
  {"category":"Verbal Ability","prompt":"Aling salita ang dapat may kapital na titik?","optionA":"A. pilipinas","optionB":"B. lungsod","optionC":"C. bansa","optionD":"D. lalawigan","answerIndex":0,"explanation":"Ang 'pilipinas' ay pangngalang pantangi (proper noun) kaya dapat magsimula sa malaking titik."},
  {"category":"Verbal Ability","prompt":"Which sentence correctly uses an apostrophe for possession?","optionA":"A. The employees' lockers were placed in the lounge.","optionB":"B. The employee's lockers were placed in the lounge.","optionC":"C. The employees locker's were placed in the lounge.","optionD":"D. The employees lockers' were placed in the lounge.","answerIndex":0,"explanation":"Plural noun ending in 's' ('employees') takes an apostrophe after the 's'."},
  {"category":"Verbal Ability","prompt":"Aling bantas ang ginagamit sa paghihiwalay ng magkakasunod na sugnay o kaisipan?","optionA":"A. Koma o kuwit (,)","optionB":"B. Tuldok (.)","optionC":"C. Tandang pananong (?)","optionD":"D. Gitling (-)","answerIndex":0,"explanation":"Ang kuwit (,) ay ginagamit sa paghihiwalay ng mga lipon ng salita sa loob ng pangungusap."}
];

// BATCH 3: SENTENCE SKILLS (50 ITEMS)
const batch3 = [
  {"category":"Verbal Ability","prompt":"Despite the budget constraints, the team managed to produce an _____ proposal that impressed the executive board.","optionA":"A. inadequate","optionB":"B. exemplary","optionC":"C. ordinary","optionD":"D. obscure","answerIndex":1,"explanation":"'Exemplary' (outstanding) fits the contrast introduced by 'Despite budget constraints'."},
  {"category":"Verbal Ability","prompt":"Ang mamamayan na may pagnanais na makatulong sa lipunan ay dapat maging _____ sa pagsunod sa mga batas.","optionA":"A. pasaway","optionB":"B. matapat","optionC":"C. pabaya","optionD":"D. mabilis","answerIndex":1,"explanation":"Ang 'matapat' ay ang angkop na katangian ng isang mamamayang sumusunod sa batas."},
  {"category":"Verbal Ability","prompt":"Scarcely had the press conference ended _____ the official memo was distributed to news outlets.","optionA":"A. than","optionB":"B. when","optionC":"C. then","optionD":"D. that","answerIndex":1,"explanation":"'Scarcely... when' is a standard correlative structure in formal English."},
  {"category":"Verbal Ability","prompt":"Kahit na marami ang pagsubok, hindi kailanman _____ ang kanyang mithiin na makapagtapos ng pag-aaral.","optionA":"A. natuloy","optionB":"B. natinag","optionC":"C. lumago","optionD":"D. lumabas","answerIndex":1,"explanation":"Ang 'natinag' (nasira/naalis) ay angkop sa pariralang 'kahit na marami ang pagsubok'."},
  {"category":"Verbal Ability","prompt":"The research findings were so _____ that even the skeptics were convinced of the drug's safety.","optionA":"A. ambiguous","optionB":"B. conclusive","optionC":"C. doubtful","optionD":"D. trivial","answerIndex":1,"explanation":"Convincing skeptics requires 'conclusive' (decisive) evidence."},
  {"category":"Verbal Ability","prompt":"Dapat tayong maging _____ sa pagpili ng mga lider na mamumuno sa ating bansa.","optionA":"A. mapagmatyag","optionB":"B. madasalin","optionC":"C. mainitin","optionD":"D. masungit","answerIndex":0,"explanation":"Ang 'mapagmatyag' (vigilant) ay angkop na katangian sa pagpili ng namumuno."},
  {"category":"Verbal Ability","prompt":"Neither the manager nor the supervisors _____ available to comment on the policy change.","optionA":"A. was","optionB":"B. were","optionC":"C. is","optionD":"D. has been","answerIndex":1,"explanation":"'Were' agrees with plural 'supervisors' closest to the verb in 'neither... nor'."},
  {"category":"Verbal Ability","prompt":"Higit na _____ ang pamumuhay ng mga tao kung may kapayapaan sa pamayanan.","optionA":"A. tahimik","optionB":"B. masagana","optionC":"C. maayos","optionD":"D. Lahat ng nabanggit","answerIndex":3,"explanation":"Lahat ng nabanggit ay angkop na naglalarawan sa pamumuhay na may kapayapaan."},
  {"category":"Verbal Ability","prompt":"The new software is designed to _____ repetitive Administrative tasks and save time.","optionA":"A. complicate","optionB":"B. automate","optionC":"C. hinder","optionD":"D. prolong","answerIndex":1,"explanation":"Saving time and replacing repetitive tasks refers to 'automate'."},
  {"category":"Verbal Ability","prompt":"Ang pagkakaisa ng mga mamamayan ay _____ sa tagumpay ng anumang proyekto ng pamahalaan.","optionA":"A. hadlang","optionB":"B. susi","optionC":"C. sanhi ng gulo","optionD":"D. kawalan","answerIndex":1,"explanation":"Ang 'susi' ay metaphorical term para sa pundasyon ng tagumpay."},
  {"category":"Verbal Ability","prompt":"Identify the underlined part that contains an error: (A) The number of (B) applicants (C) have increased (D) significantly this year.","optionA":"A. The number of","optionB":"B. applicants","optionC":"C. have increased","optionD":"D. significantly this year","answerIndex":2,"explanation":"'The number of' takes a singular verb ('has increased'). C is erroneous."},
  {"category":"Verbal Ability","prompt":"Tukuyin ang bahaging may mali sa pangungusap: (A) Ang mga bata (B) ay masayang (C) naglalaro (D) sa bakuran kahapon.","optionA":"A. Ang mga bata","optionB":"B. ay masayang","optionC":"C. naglalaro","optionD":"D. sa bakuran kahapon","answerIndex":2,"explanation":"Dahil sa salitang 'kahapon', dapat ay naganap na kilos ang ginamit. C ang may mali."},
  {"category":"Verbal Ability","prompt":"Identify the error: (A) Had I known (B) about the emergency, (C) I would have (D) went earlier.","optionA":"A. Had I known","optionB":"B. about the emergency","optionC":"C. I would have","optionD":"D. went earlier","answerIndex":3,"explanation":"'Would have' takes past participle 'gone', not 'went'. D is erroneous."},
  {"category":"Verbal Ability","prompt":"Tukuyin ang bahaging may mali: (A) Sila ay (B) nagpunta sa (C) palengke para (D) bumili ng mga prutas.","optionA":"A. Sila ay","optionB":"B. nagpunta sa","optionC":"C. palengke para","optionD":"D. Walang mali","answerIndex":3,"explanation":"Ang pangungusap ay ganap na tama (Walang mali)."},
  {"category":"Verbal Ability","prompt":"Identify the error: (A) She dances (B) more graceful (C) than anyone else (D) in the academy.","optionA":"A. She dances","optionB":"B. more graceful","optionC":"C. than anyone else","optionD":"D. in the academy","answerIndex":1,"explanation":"Modifying the verb 'dances' requires adverb 'more gracefully'. B is erroneous."},
  {"category":"Verbal Ability","prompt":"Tukuyin ang mali: (A) Ang pamahalaan (B) ay patuloy na (C) tumutulong sa (D) mga dukha na mamamayan.","optionA":"A. Ang pamahalaan","optionB":"B. ay patuloy na","optionC":"C. tumutulong sa","optionD":"D. Walang mali","answerIndex":3,"explanation":"Wasto ang buong pangungusap (Walang mali)."},
  {"category":"Verbal Ability","prompt":"Identify the error: (A) Neither of the two (B) proposals (C) were accepted (D) by the panel.","optionA":"A. Neither of the two","optionB":"B. proposals","optionC":"C. were accepted","optionD":"D. by the panel","answerIndex":2,"explanation":"'Neither' requires singular verb 'was accepted'. C is the error."},
  {"category":"Verbal Ability","prompt":"Tukuyin ang mali: (A) Bawat isa (B) sa kanila (C) ay mayroong (D) tungkulin sa bayan.","optionA":"A. Bawat isa","optionB":"B. sa kanila","optionC":"C. ay mayroong","optionD":"D. Walang mali","answerIndex":3,"explanation":"Wasto ang pangungusap (Walang mali)."},
  {"category":"Verbal Ability","prompt":"Identify the error: (A) The supervisor asked (B) John and I (C) to review (D) the draft.","optionA":"A. The supervisor asked","optionB":"B. John and I","optionC":"C. to review","optionD":"D. the draft","answerIndex":1,"explanation":"'Asked' takes objective pronoun 'John and me'. B is erroneous."},
  {"category":"Verbal Ability","prompt":"Tukuyin ang mali: (A) Marami ang (B) dumalo sa (C) pagpupulong na (D) ginanap noong nakaraang linggo.","optionA":"A. Marami ang","optionB":"B. dumalo sa","optionC":"C. pagpupulong na","optionD":"D. Walang mali","answerIndex":3,"explanation":"Wasto ang pagkakabuo ng pangungusap (Walang mali)."},
  {"category":"Verbal Ability","prompt":"Which sentence exhibits proper parallel structure?","optionA":"A. She enjoys reading books, swimming in the lake, and to hike up mountains.","optionB":"B. She enjoys reading books, swimming in the lake, and hiking up mountains.","optionC":"C. She enjoys to read books, swimming in the lake, and hiking up mountains.","optionD":"D. She enjoys reading books, to swim in the lake, and hiking up mountains.","answerIndex":1,"explanation":"Parallel structure requires all listed items to use gerunds ('reading, swimming, hiking')."},
  {"category":"Verbal Ability","prompt":"Alin sa mga sumusunod ang pangungusap na may TAMAng ayos ng mga salita?","optionA":"A. Ang mga mag-aaral ay masigasig na nag-aaral.","optionB":"B. Masigasig na nag-aaral ang mga mag-aaral.","optionC":"C. Parehong A at B ay tama","optionD":"D. Wala sa nabanggit","answerIndex":2,"explanation":"Sa Filipino, parehong tama ang Karaniwang Ayos (B) at Di-Karaniwang Ayos (A)."},
  {"category":"Verbal Ability","prompt":"Which sentence avoids a dangling modifier?","optionA":"A. Walking down the street, the trees were beautiful.","optionB":"B. Walking down the street, I admired the beautiful trees.","optionC":"C. While walking down the street, the trees looked green.","optionD":"D. Having finished the test, the papers were collected.","answerIndex":1,"explanation":"The modifier 'Walking down the street' must logically attach to the subject 'I'."},
  {"category":"Verbal Ability","prompt":"Aling pangungusap ang halimbawa ng Tambalang Pangungusap?","optionA":"A. Nag-aral si Ana at nakapasa siya sa pagsusulit.","optionB":"B. Dahil nag-aral si Ana, nakapasa siya.","optionC":"C. Si Ana ay nag-aral nang mabuti.","optionD":"D. Si Ana na masipag.","answerIndex":0,"explanation":"Ang tambalang pangungusap ay binubuo ng dalawang payak na pangungusap na pinag-uugnay ng 'at'."},
  {"category":"Verbal Ability","prompt":"Which of the following is a complete compound-complex sentence?","optionA":"A. Although it was raining, we decided to go hiking, and we enjoyed the trip.","optionB":"B. It was raining and we went hiking.","optionC":"C. Although it rained, we went hiking.","optionD":"D. We went hiking despite the rain.","answerIndex":0,"explanation":"Contains two independent clauses joined by 'and' plus a dependent clause introduced by 'Although'."},
  {"category":"Verbal Ability","prompt":"Aling pangungusap ang may HINDI wastong ayos?","optionA":"A. Pumasok sa silid ang guro.","optionB":"B. Ang guro ay pumasok sa silid.","optionC":"C. Pumasok ang guro sa silid.","optionD":"D. Sa silid pumasok ang guro ay.","answerIndex":3,"explanation":"Ang 'Sa silid pumasok ang guro ay' ay hindi malinaw at mali ang balangkas."},
  {"category":"Verbal Ability","prompt":"Which sentence correctly avoids a comma splice?","optionA":"A. The deadline is tomorrow, we must work overtime.","optionB":"B. The deadline is tomorrow; therefore, we must work overtime.","optionC":"C. The deadline is tomorrow, therefore we must work overtime.","optionD":"D. The deadline is tomorrow we must work overtime.","answerIndex":1,"explanation":"Joining independent clauses with 'therefore' requires a semicolon before it and a comma after."},
  {"category":"Verbal Ability","prompt":"Alin sa mga sumusunod ang Payak na Pangungusap?","optionA":"A. Naglinis ng bahay si Maria.","optionB":"B. Naglinis ng bahay si Maria samantalang nagluto si Pedro.","optionC":"C. Kapag natapos si Maria, kakain na kami.","optionD":"D. Si Maria ay naglinis at si Pedro ay nagluto.","answerIndex":0,"explanation":"Ang payak na pangungusap ay nagpapahayag ng iisang kaisipan lamang."},
  {"category":"Verbal Ability","prompt":"Select the sentence with no misplaced modifiers.","optionA":"A. Covered in hot fudge, the boy ate the ice cream sundae.","optionB":"B. The boy ate the ice cream sundae covered in hot fudge.","optionC":"C. The boy ate covered in hot fudge the ice cream sundae.","optionD":"D. Covered in hot fudge the boy Sundae ate.","answerIndex":1,"explanation":"'Covered in hot fudge' correctly modifies 'the ice cream sundae' in Option B."},
  {"category":"Verbal Ability","prompt":"Ano ang tinatawag na 'Simuno' o 'Paksa' sa pangungusap?","optionA":"A. Ang bahaging nagbibigay-linaw sa pandiwa","optionB":"B. Ang pinag-uusapan sa pangungusap","optionC":"C. Ang kilos na ginagawa","optionD":"D. Ang lugar ng pinangyarihan","answerIndex":1,"explanation":"Ang simuno o paksa ay ang bahaging pinag-uusapan sa pangungusap."},
  {"category":"Verbal Ability","prompt":"Choose the sentence that demonstrates grammatically correct usage.","optionA":"A. Their going to submit there reports over where.","optionB":"B. They're going to submit their reports over there.","optionC":"C. There going to submit their reports over they're.","optionD":"D. They're going to submit there reports over their.","answerIndex":1,"explanation":"'They're' (they are), 'their' (possessive), and 'there' (place) are used correctly in Option B."},
  {"category":"Verbal Ability","prompt":"Alin sa mga sumusunod ang TAMAng paggamit ng 'NG' at 'NANG'?","optionA":"A. Nag-aral siya ng mabuti upang makapasa.","optionB":"B. Nag-aral siya nang mabuti upang makapasa.","optionC":"C. Kumain siya nang saging.","optionD":"D. Uminom siya nang tubig.","answerIndex":1,"explanation":"Ang 'nang' ay ginagamit na pang-abay na pamanahon/pamaraan ('nang mabuti')."},
  {"category":"Verbal Ability","prompt":"Choose the correct sentence.","optionA":"A. The reason why he left is because he was tired.","optionB":"B. The reason he left is that he was tired.","optionC":"C. The reason why he left is due to he was tired.","optionD":"D. The reason for him leaving is because of tiredness.","answerIndex":1,"explanation":"'The reason... is that' avoids the redundant 'reason is because' construction."},
  {"category":"Verbal Ability","prompt":"Alin ang TAMAng paggamit ng 'DIN' at 'RIN'?","optionA":"A. Ako rin ay pupunta sa pamilihan.","optionB":"B. Ako din ay pupunta sa pamilihan.","optionC":"C. Ikaw rin ay kasama.","optionD":"D. Parehong A at C","answerIndex":3,"explanation":"Ang 'rin' ay ginagamit kapag ang sinusundang salita ay nagtatapos sa patinig ('Ako rin', 'Ikaw rin')."},
  {"category":"Verbal Ability","prompt":"Choose the sentence with correct subject-verb agreement and pronoun reference.","optionA":"A. Every one of the students must bring their own calculator.","optionB":"B. Every one of the students must bring his or her own calculator.","optionC":"C. Every one of the students must bring their own calculators.","optionD":"D. Every one of the students have to bring their calculator.","answerIndex":1,"explanation":"'Every one' is singular, requiring 'his or her' in traditional formal grammar."},
  {"category":"Verbal Ability","prompt":"Alin ang TAMAng paggamit ng 'MAY' at 'MAYROON'?","optionA":"A. Mayroong tao sa labas ng bahay.","optionB":"B. May tao sa labas ng bahay.","optionC":"C. Mayroong magagandang bulaklak dito.","optionD":"D. May pera ka ba sa mayroong bulsa?","answerIndex":1,"explanation":"Ang 'may' ay ginagamit kapag ang kasunod na salita ay pangngalan ('tao')."},
  {"category":"Verbal Ability","prompt":"Select the sentence free of structural errors.","optionA":"A. Neither the manager nor the clerks was pleased with the result.","optionB":"B. Neither the manager nor the clerks were pleased with the result.","optionC":"C. Neither the clerks nor the manager were pleased with the result.","optionD":"D. Neither the manager or the clerks were pleased.","answerIndex":1,"explanation":"'Were' agrees with the plural subject 'clerks' nearest to the verb in 'neither... nor'."},
  {"category":"Verbal Ability","prompt":"Aling pangungusap ang gumagamit ng wastong salita sa pagtukoy ng kinaroroonan?","optionA":"A. Subukin natin ang bagong resipe.","optionB":"B. Subukan natin ang bagong resipe.","optionC":"C. Subukin mo siya kung tapat.","optionD":"D. Parehong A at C ay tama","answerIndex":3,"explanation":"Ang 'subukin' ay pagsusuri sa kakayahan/katapatan, samantalang ang 'subukan' ay pagsubok sa bagay."},
  {"category":"Verbal Ability","prompt":"Select the correct sentence.","optionA":"A. Irregardless of the outcome, we will proceed.","optionB":"B. Regardless of the outcome, we will proceed.","optionC":"C. Regardless about the outcome, we will proceed.","optionD":"D. Irregardless about the outcome, we will proceed.","answerIndex":1,"explanation":"'Irregardless' is nonstandard; 'Regardless of' is correct."},
  {"category":"Verbal Ability","prompt":"Alin sa mga sumusunod ang TAMAng paggamit ng 'PINTO' at 'PINTUAN'?","optionA":"A. Isara mo ang pintuan.","optionB":"B. Isara mo ang pinto.","optionC":"C. Pumasok ka sa pinto.","optionD":"D. Pintuan ang ginagamit sa pagharang.","answerIndex":1,"explanation":"Ang 'pinto' (door) ay ang mismong natatakpan/naisasara, samantalang ang 'pintuan' (doorway) ay ang daanan."},
  {"category":"Verbal Ability","prompt":"Choose the grammatically correct sentence.","optionA":"A. Less people attended the concert this year than last year.","optionB":"B. Fewer people attended the concert this year than last year.","optionC":"C. Lesser people attended the concert this year than last year.","optionD":"D. Few people attended the concert this year as last year.","answerIndex":1,"explanation":"'Fewer' is used for countable nouns ('people')."},
  {"category":"Verbal Ability","prompt":"Aling pangungusap ang may TAMAng paggamit ng 'SUBUKIN'?","optionA":"A. Subukin mo ang lasa ng sabaw.","optionB":"B. Subukin natin ang katapatan ng bagong kawani.","optionC":"C. Subukin natin kung naroon siya sa kwarto.","optionD":"D. Subukin mo ang damit kung kasya.","answerIndex":1,"explanation":"Ang 'subukin' ay nangangahulugang siyasatin ang katapatan o kakayahan ng tao."},
  {"category":"Verbal Ability","prompt":"Select the correct sentence.","optionA":"A. I could care less about their opinion.","optionB":"B. I couldn't care less about their opinion.","optionC":"C. I couldn't care more about their opinion.","optionD":"D. I could care fewer about their opinion.","answerIndex":1,"explanation":"The idiom expressing total indifference is 'I couldn't care less'."},
  {"category":"Verbal Ability","prompt":"Alin ang may wastong gamit ng 'KITA' at 'KATA'?","optionA":"A. Nakita kita sa parke kahapon.","optionB":"B. Kita ay pupunta sa Maynila.","optionC":"C. Nakita kata sa parke.","optionD":"D. Kata ay magkaibigan.","answerIndex":0,"explanation":"Ang 'kita' ay nangangahulugang 'ko ikaw' ('Nakita ko ikaw' -> 'Nakita kita')."},
  {"category":"Verbal Ability","prompt":"Select the sentence with correct verb agreement.","optionA":"A. Statistics is a required subject for business students.","optionB":"B. Statistics are a required subject for business students.","optionC":"C. Statistics were a required subject for business students.","optionD":"D. Statistics have been a required subject.","answerIndex":0,"explanation":"Academic disciplines ending in 's' ('Statistics') take singular verbs ('is')."},
  {"category":"Verbal Ability","prompt":"Alin ang TAMAng paggamit ng 'PAHIRIN' at 'PAHIRAN'?","optionA":"A. Pahirin mo ang luha sa iyong mga mata.","optionB":"B. Pahiran mo ang luha sa iyong mga mata.","optionC":"C. Pahirin mo ng langis ang kanyang likod.","optionD":"D. Pahirin mo ang mantikilya sa tinapay.","answerIndex":0,"explanation":"Ang 'pahirin' ay nangangahulugang alisin ang bagay ('luha'), samantalang ang 'pahiran' ay lagyan."},
  {"category":"Verbal Ability","prompt":"Choose the correctly written sentence.","optionA":"A. The data shows that revenues increased.","optionB":"B. The data show that revenues increased.","optionC":"C. The data is showing that revenues increased.","optionD":"D. The datas show that revenues increased.","answerIndex":1,"explanation":"In formal scientific writing, 'data' is the plural of 'datum' and takes 'show'."},
  {"category":"Verbal Ability","prompt":"Alin ang TAMAng gamit ng 'OPERAHIN' at 'OPERAHAN'?","optionA":"A. Operahin ang kanyang apendiks.","optionB":"B. Operahan ang kanyang apendiks.","optionC":"C. Operahin ang tiyan ng pasyente.","optionD":"D. Operahin ang buong katawan.","answerIndex":0,"explanation":"Ang 'operahin' ay tumutukoy sa partikular na bahagi ng katawan na aalisin o gagamutin ('apendiks')."},
  {"category":"Verbal Ability","prompt":"Choose the sentence with proper modifier placement.","optionA":"A. She almost drove six hundred miles today.","optionB":"B. She drove almost six hundred miles today.","optionC":"C. She drove six hundred miles almost today.","optionD":"D. Almost she drove six hundred miles today.","answerIndex":1,"explanation":"'Almost' correctly modifies the distance 'six hundred miles' in Option B."},
  {"category":"Verbal Ability","prompt":"Alin sa mga sumusunod ang TAMAng pahayag?","optionA":"A. Walang mahirap sa taong masipag.","optionB":"B. Ang taong masipag ay walang mahirap.","optionC":"C. Masipag ang taong walang mahirap.","optionD":"D. Mahirap ang taong walang masipag.","answerIndex":0,"explanation":"Ang 'Walang mahirap sa taong masipag' ay ang kilalang wastong kasabihan sa Filipino."}
];

// BATCH 4: READING SKILLS (50 ITEMS)
const batch4 = [
  {"category":"Verbal Ability","prompt":"Arrange the following sentences to form a logical paragraph:\n(1) Consequently, productivity increased by 25 percent.\n(2) The company introduced flexible working hours last month.\n(3) Employees reported lower stress levels and greater job satisfaction.\n(4) This policy allowed workers to balance personal and professional duties.","optionA":"A. (2)-(4)-(3)-(1)","optionB":"B. (1)-(2)-(3)-(4)","optionC":"C. (3)-(2)-(4)-(1)","optionD":"D. (4)-(2)-(1)-(3)","answerIndex":0,"explanation":"Logical order: Introduce event (2) -> Explain benefit (4) -> Employee reaction (3) -> Final result (1)."},
  {"category":"Verbal Ability","prompt":"Ayusin ang mga sumusunod na pangungusap upang makabuo ng lohikal na talata:\n(1) Dahil dito, mabilis na umunlad ang kabuhayan ng baryo.\n(2) Nagkaisa ang mga mamamayan na magtayo ng isang kooperatiba.\n(3) Nagsimula sila sa pamamagitan ng pag-iipon ng maliliit na ambag.\n(4) Ginamit ang naipong pondo upang magsimula ng lokal na negosyo.","optionA":"A. (2)-(3)-(4)-(1)","optionB":"B. (1)-(2)-(3)-(4)","optionC":"C. (4)-(3)-(2)-(1)","optionD":"D. (3)-(4)-(1)-(2)","answerIndex":0,"explanation":"Lohikal na pagkakasunod: Panimula (2) -> Unang hakbang (3) -> Paggamit sa pondo (4) -> Bunga (1)."},
  {"category":"Verbal Ability","prompt":"Arrange the sentences in logical order:\n(1) First, wash your hands thoroughly with soap and water.\n(2) Next, sanitize all kitchen utensils before preparing food.\n(3) Finally, serve the meal while it is hot and fresh.\n(4) Then, cook the ingredients according to the recipe instructions.","optionA":"A. (1)-(2)-(4)-(3)","optionB":"B. (4)-(3)-(2)-(1)","optionC":"C. (2)-(1)-(4)-(3)","optionD":"D. (1)-(4)-(2)-(3)","answerIndex":0,"explanation":"Sequence markers: First (1) -> Next (2) -> Then (4) -> Finally (3)."},
  {"category":"Verbal Ability","prompt":"Ayusin ang mga pangungusap upang makabuo ng lohikal na talakayan:\n(1) Sa wakas, naipasa rin ang panukalang batas sa senado.\n(2) Nagsimula ang talakayan sa mababang kapulungan ng kongreso.\n(3) Matapos ang masusing pag-aaral, ipinasa ito sa ikalawang pagbasa.\n(4) Isinailalim ito sa maraming serye ng pampublikong pagdinig.","optionA":"A. (2)-(4)-(3)-(1)","optionB":"B. (1)-(2)-(3)-(4)","optionC":"C. (3)-(4)-(2)-(1)","optionD":"D. (4)-(2)-(1)-(3)","answerIndex":0,"explanation":"Proseso ng batas: Simula sa kongreso (2) -> Pagdinig (4) -> Ikalawang pagbasa (3) -> Pasa sa senado (1)."},
  {"category":"Verbal Ability","prompt":"Arrange the sentences to form a coherent text:\n(1) In conclusion, digital literacy is essential for modern employment.\n(2) Employers now seek candidates who can easily navigate digital tools.\n(3) Furthermore, automation has reshaped traditional office roles.\n(4) Technology has transformed the workplace dramatically in recent years.","optionA":"A. (4)-(3)-(2)-(1)","optionB":"B. (1)-(2)-(3)-(4)","optionC":"C. (2)-(4)-(1)-(3)","optionD":"D. (3)-(1)-(4)-(2)","answerIndex":0,"explanation":"General statement (4) -> Point on automation (3) -> Employer perspective (2) -> Conclusion (1)."},
  {"category":"Verbal Ability","prompt":"Ayusin ang mga pangungusap:\n(1) Bukod dito, ang pagtatanim ng puno ay tumutulong laban sa pagbaha.\n(2) Ang kalikasan ay nangangailangan ng ating pangangalaga.\n(3) Kaya naman, nararapat lamang na lumahok tayo sa mga tree-planting activity.\n(4) Ang mga puno ay nagbibigay ng malinis na hangin at lilim.","optionA":"A. (2)-(4)-(1)-(3)","optionB":"B. (1)-(2)-(3)-(4)","optionC":"C. (3)-(4)-(2)-(1)","optionD":"D. (4)-(1)-(3)-(2)","answerIndex":0,"explanation":"Pangunahing ideya (2) -> Unang dahilan (4) -> Karagdagang dahilan (1) -> Panawagan (3)."},
  {"category":"Verbal Ability","prompt":"Arrange the sentences in logical chronological order:\n(1) She was awarded Employee of the Year during the annual gala.\n(2) Maria joined the corporation as an entry-level analyst in 2018.\n(3) Recognizing her dedication, the executive board promoted her to Senior Manager.\n(4) Over the next three years, she consistently exceeded project performance targets.","optionA":"A. (2)-(4)-(3)-(1)","optionB":"B. (1)-(2)-(3)-(4)","optionC":"C. (4)-(3)-(2)-(1)","optionD":"D. (3)-(1)-(2)-(4)","answerIndex":0,"explanation":"Chronological flow: Joined in 2018 (2) -> Performance (4) -> Promotion (3) -> Award (1)."},
  {"category":"Verbal Ability","prompt":"Ayusin ang mga pangungusap:\n(1) Matapos ang dalawang oras na biyahe, nakarating din kami sa tuktok.\n(2) Maaga kaming gumising upang maghanda sa pag-akyat sa bundok.\n(3) Mula sa itaas, kitang-kita ang magandang tanawin ng buong lungsod.\n(4) Bitbit ang aming mga bag, sinimulan namin ang paglalakad sa landas.","optionA":"A. (2)-(4)-(1)-(3)","optionB":"B. (1)-(2)-(3)-(4)","optionC":"C. (3)-(1)-(4)-(2)","optionD":"D. (4)-(2)-(1)-(3)","answerIndex":0,"explanation":"Pagkakasunod: Paghahanda (2) -> Simula ng lakad (4) -> Pagdating sa tuktok (1) -> Tanawin (3)."},
  {"category":"Verbal Ability","prompt":"Arrange the sentences:\n(1) Therefore, saving money regularly from a young age is crucial.\n(2) Financial independence requires long-term planning and discipline.\n(3) Compound interest enables small savings to grow significantly over time.\n(4) Without savings, unexpected medical or personal emergencies can lead to debt.","optionA":"A. (2)-(3)-(4)-(1)","optionB":"B. (1)-(2)-(3)-(4)","optionC":"C. (4)-(1)-(2)-(3)","optionD":"D. (3)-(4)-(1)-(2)","answerIndex":0,"explanation":"Main principle (2) -> Positive benefit (3) -> Negative risk (4) -> Concluding action (1)."},
  {"category":"Verbal Ability","prompt":"Ayusin ang mga pangungusap:\n(1) Sa gayon, napanatili ang kalinisan at kaayusan sa buong pamayanan.\n(2) Nagpatupad ang barangay ng tamang paghihiwalay ng basura.\n(3) Bawat tahanan ay binigyan ng tatlong magkakahiwalay na basurahan.\n(4) Nagkaroon din ng lingguhang koleksyon ng mga nabubulok na basura.","optionA":"A. (2)-(3)-(4)-(1)","optionB":"B. (1)-(2)-(3)-(4)","optionC":"C. (4)-(3)-(2)-(1)","optionD":"D. (3)-(2)-(1)-(4)","answerIndex":0,"explanation":"Proseso: Panukala ng barangay (2) -> Pagbibigay ng basurahan (3) -> Koleksyon (4) -> Bunga (1)."},
  {"category":"Verbal Ability","prompt":"Passage: Civil service employees play a vital role in nation-building by executing government policies with integrity, efficiency, and dedication. Under Republic Act No. 6713, also known as the Code of Conduct and Ethical Standards for Public Officials and Employees, civil servants are mandated to uphold public interest over personal gain at all times.\n\nQuestion: What is the main idea of the passage?","optionA":"A. Civil servants are exempt from legal regulations.","optionB":"B. Public officials are required to uphold ethical standards and public interest in nation-building.","optionC":"C. Republic Act No. 6713 was recently repealed by Congress.","optionD":"D. Private sector employment is superior to public service.","answerIndex":1,"explanation":"The passage highlights the vital role of civil servants and their legal mandate under R.A. 6713."},
  {"category":"Verbal Ability","prompt":"Passage: Civil service employees play a vital role in nation-building... Under Republic Act No. 6713...\n\nQuestion: What is R.A. 6713 officially known as?","optionA":"A. The Civil Service Reform Act","optionB":"B. The Code of Conduct and Ethical Standards for Public Officials and Employees","optionC":"C. The Anti-Graft and Corrupt Practices Act","optionD":"D. The Local Government Code","answerIndex":1,"explanation":"The text explicitly states that R.A. 6713 is the 'Code of Conduct and Ethical Standards for Public Officials and Employees'."},
  {"category":"Verbal Ability","prompt":"Passage: Civil service employees play a vital role in nation-building...\n\nQuestion: According to the passage, what must civil servants prioritize over personal gain?","optionA":"A. Political party preferences","optionB":"B. Public interest","optionC":"C. Financial investments","optionD":"D. Personal promotions","answerIndex":1,"explanation":"The passage explicitly states that employees are mandated to 'uphold public interest over personal gain'."},
  {"category":"Verbal Ability","prompt":"Passage: Civil service employees play a vital role in nation-building...\n\nQuestion: What is the author's primary purpose in writing this passage?","optionA":"A. To criticize government employees","optionB":"B. To inform readers about the ethical duties and importance of civil servants","optionC":"C. To promote a political campaign","optionD":"D. To encourage civil servants to resign","answerIndex":1,"explanation":"The tone is informative and objective, explaining the legal and ethical duties of public servants."},
  {"category":"Verbal Ability","prompt":"Passage: Civil service employees play a vital role in nation-building...\n\nQuestion: What conclusion can be drawn regarding a public employee who uses government property for personal profit?","optionA":"A. They are following R.A. 6713.","optionB":"B. They are violating the ethical standard of prioritizing public interest over personal gain.","optionC":"C. They deserve an immediate promotion.","optionD":"D. They are fulfilling nation-building goals.","answerIndex":1,"explanation":"Using government assets for personal profit directly contradicts prioritizing public interest over personal gain."},
  {"category":"Verbal Ability","prompt":"Babasahin: Ang edukasyon ay ang pinakamahalagang pamana ng isang magulang sa kanyang anak. Sa pamamagitan ng sapat na kaalaman at kasanayan, nagkakaroon ang isang indibidwal ng kakayahang maabot ang kanyang mga pangarap at maging kapaki-pakinabang na mamamayan sa lipunan. Hindi man ito nananakaw ng sinuman, kailangan pa rin ng tiyaga at disiplina upang ito ay matapos.\n\nTanong: Ano ang pangunahing paksa ng talata?","optionA":"A. Ang kahalagahan ng edukasyon at ang mga katangiang kailangan para maabot ito","optionB":"B. Ang mataas na halaga ng matrikula sa paaralan","optionC":"C. Ang kawalan ng trabaho sa bansa","optionD":"D. Ang mga uri ng kurso sa kolehiyo","answerIndex":0,"explanation":"Tinatatalakay sa buong talata ang kahalagahan ng edukasyon bilang pamana at ang tiyagang kailangan dito."},
  {"category":"Verbal Ability","prompt":"Babasahin: Ang edukasyon ay ang pinakamahalagang pamana ng isang magulang sa kanyang anak...\n\nTanong: Ayon sa talata, bakit sinasabing ang edukasyon ay isang magandang pamana?","optionA":"A. Dahil ito ay madaling makuha nang walang paghihirap","optionB":"B. Dahil hindi ito nananakaw at nagbibigay ng kakayahang maabot ang pangarap","optionC":"C. Dahil ito ay nabibili sa murang halaga","optionD":"D. Dahil ito ay panandalian lamang","answerIndex":1,"explanation":"Maliwanag na sinabi na hindi ito nananakaw at nagbibigay ng kakayahang maging kapaki-pakinabang."},
  {"category":"Verbal Ability","prompt":"Babasahin: Ang edukasyon ay ang pinakamahalagang pamana ng isang magulang sa kanyang anak...\n\nTanong: Anong mga katangian ang kailangan ayon sa talata upang matapos ang edukasyon?","optionA":"A. Yabang at lakas","optionB":"B. Tiyaga at disiplina","optionC":"C. Yaman at katanyagan","optionD":"D. Bilis at swerte","answerIndex":1,"explanation":"Binanggit sa huling pangungusap na kailangan ng 'tiyaga at disiplina'."},
  {"category":"Verbal Ability","prompt":"Babasahin: Ang edukasyon ay ang pinakamahalagang pamana ng isang magulang sa kanyang anak...\n\nTanong: Ano ang layunin ng may-akda sa pagsulat ng talatang ito?","optionA":"A. Mangaral at manghikayat na pahalagahan ang edukasyon","optionB":"B. Manira ng reputasyon ng mga paaralan","optionC":"C. Magbenta ng mga kagamitan sa pag-aaral","optionD":"D. Magreklamo sa pamahalaan","answerIndex":0,"explanation":"Ang layunin ng may-akda ay ihayag ang halaga ng edukasyon at manghikayat na magsumikap."},
  {"category":"Verbal Ability","prompt":"Babasahin: Ang edukasyon ay ang pinakamahalagang pamana ng isang magulang sa kanyang anak...\n\nTanong: Ano ang mahihinuha tungkol sa isang taong may sapat na edukasyon at disiplina?","optionA":"A. Mas malaki ang tsansa niyang maging kapaki-pakinabang na mamamayan.","optionB":"B. Siguradong magiging mayaman siya agad nang walang trabaho.","optionC":"C. Hindi na siya kailanman magkakamali.","optionD":"D. Hindi na niya kailangan ang ibang tao.","answerIndex":0,"explanation":"Ayon sa teksto, ang edukasyon ay nagbibigay ng kakayahang maging kapaki-pakinabang na mamamayan."},
  {"category":"Verbal Ability","prompt":"Passage: Renewable energy sources, such as solar and wind power, offer a sustainable alternative to fossil fuels. By generating electricity without producing greenhouse gases, these technologies significantly reduce air pollution and mitigate global climate change.\n\nQuestion: Which supporting detail explains HOW renewable energy combats climate change?","optionA":"A. By lowering the price of gasoline","optionB":"B. By generating electricity without producing greenhouse gases","optionC":"C. By increasing coal production","optionD":"D. By building larger power grids","answerIndex":1,"explanation":"The text explicitly states: 'By generating electricity without producing greenhouse gases...'"},
  {"category":"Verbal Ability","prompt":"Passage: Renewable energy sources, such as solar and wind power, offer a sustainable alternative to fossil fuels.\n\nQuestion: What is the author's attitude/tone toward renewable energy?","optionA":"A. Skeptical and hostile","optionB":"B. Positive and supportive","optionC":"C. Indifferent and bored","optionD":"D. Sarcastic and critical","answerIndex":1,"explanation":"Describing renewable energy as 'sustainable' and mitigating climate change reflects a positive, supportive tone."},
  {"category":"Verbal Ability","prompt":"Babasahin: Ang kalusugan ay kayamanan. Ang pagkuha ng sapat na tulog, pagkain ng masustansyang pagkain, at regular na pag-eehersisyo ay mga simpleng hakbang upang makaiwas sa iba't ibang uri ng karamdaman.\n\nTanong: Ano ang pangunahing kaisipan ng babasahin?","optionA":"A. Ang mamahaling gamot ang tanging gamot sa sakit.","optionB":"B. Ang malusog na pamumuhay ay mahalaga upang makaiwas sa sakit.","optionC":"C. Ang pagtulog ay mas mahalaga kaysa sa pag-eehersisyo.","optionD":"D. Ang ospital ay para sa lahat.","answerIndex":1,"explanation":"Ang pangunahing kaisipan ay ang pagpapanatili ng kalusugan sa pamamagitan ng masustansyang pamumuhay."},
  {"category":"Verbal Ability","prompt":"Babasahin: Ang kalusugan ay kayamanan. Ang pagkuha ng sapat na tulog, pagkain ng masustansyang pagkain, at regular na pag-eehersisyo ay mga simpleng hakbang upang makaiwas sa sakit.\n\nTanong: Alin sa mga sumusunod ang HINDI nabanggit na paraan ng pagpapanatili ng kalusugan?","optionA":"A. Sapat na tulog","optionB":"B. Pag-inom ng vitamins araw-araw","optionC":"C. Masustansyang pagkain","optionD":"D. Regular na pag-eehersisyo","answerIndex":1,"explanation":"Ang 'pag-inom ng vitamins' ay hindi direktang nabanggit sa maikling teksto."},
  {"category":"Verbal Ability","prompt":"Passage: Electronic governance (e-governance) streamlines public service delivery by enabling citizens to access government permits, clearances, and documents online. This reduces long queues at agency offices and minimizes bureaucratic corruption.\n\nQuestion: What is the main topic of the text?","optionA":"A. The disadvantages of internet usage","optionB":"B. How e-governance improves efficiency and reduces corruption in public service","optionC":"C. The cost of computer hardware in government offices","optionD":"D. The history of postal services in the Philippines","answerIndex":1,"explanation":"The text explains how e-governance streamlines public services and minimizes corruption."},
  {"category":"Verbal Ability","prompt":"Passage: Electronic governance streamlines public service delivery by enabling citizens to access permits online.\n\nQuestion: What conclusion can be inferred from the passage?","optionA":"A. Online government services make transaction processing faster and more transparent.","optionB":"B. Citizens prefer waiting in long physical queues.","optionC":"C. E-governance increases physical paperwork.","optionD":"D. Internet access is illegal in public offices.","answerIndex":0,"explanation":"Reducing queues and minimizing corruption implies faster and more transparent transactions."},
  {"category":"Verbal Ability","prompt":"Babasahin: Ang pagbabasa ng mga aklat ay nagpapalawak ng kaisipan at talasalitaan ng isang tao. Sa bawat pahina ng libro, natututo tayo ng mga bagong aral na magagamit sa pang-araw-araw na buhay.\n\nTanong: Ano ang layunin ng may-akda?","optionA":"A. Hikyatin ang mambabasa na magbasa ng mga aklat","optionB":"B. Ipagbawal ang pagbasa sa mga kabataan","optionC":"C. Ipagbenta ang kanyang sariling libro","optionD":"D. Batikusin ang mga babasahin sa internet","answerIndex":0,"explanation":"Ang positibong paglalarawan sa pagbabasa ay naglalayong manghikayat na magbasa."},
  {"category":"Verbal Ability","prompt":"Passage: Water conservation is essential during the dry season. Simple habits, such as fixing leaky faucets immediately and reusing dishwater for plants, can save thousands of liters of clean water annually.\n\nQuestion: Which of the following is a supporting detail mentioned in the text?","optionA":"A. Drinking eight glasses of water daily","optionB":"B. Fixing leaky faucets immediately","optionC":"C. Washing cars with a high-pressure hose","optionD":"D. Boiling water before drinking","answerIndex":1,"explanation":"Fixing leaky faucets is explicitly listed as a simple water-saving habit."},
  {"category":"Verbal Ability","prompt":"Passage: Water conservation is essential during the dry season.\n\nQuestion: What is the main idea of the passage?","optionA":"A. Leaky faucets are very expensive to buy.","optionB":"B. Simple conservation habits help prevent water waste during the dry season.","optionC":"C. Rainwater is unsafe for plants.","optionD":"D. Water companies should double their rates.","answerIndex":1,"explanation":"The passage centers on simple daily habits to conserve water during dry periods."},
  {"category":"Verbal Ability","prompt":"Babasahin: Ang disiplina sa trapiko ay responsibilidad ng bawat drayber at pedestrian. Ang pagsunod sa mga ilaw-trapiko at tamang tawiran ay nakakabawas sa aksidente sa kalsada.\n\nTanong: Sino ang responsable sa disiplina sa kalsada ayon sa teksto?","optionA":"A. Ang mga pulis lamang","optionB":"B. Ang mga drayber at pedestrian","optionC":"C. Ang pamahalaang lungsod lamang","optionD":"D. Ang mga mekaniko","answerIndex":1,"explanation":"Maliwanag na sinabi sa teksto na responsibilidad ito ng drayber at pedestrian."},
  {"category":"Verbal Ability","prompt":"Passage: Effective time management allows individuals to accomplish more tasks in less time, reducing stress and boosting career performance. Prioritizing urgent and important tasks is key to maintaining productivity.\n\nQuestion: What is the primary benefit of time management according to the text?","optionA":"A. Eliminating the need to work","optionB":"B. Accomplishing more tasks efficiently and reducing stress","optionC":"C. Increasing coffee consumption","optionD":"D. Extending office working hours","answerIndex":1,"explanation":"The text explicitly states it allows accomplishing more in less time while reducing stress."},
  {"category":"Verbal Ability","prompt":"Passage: Effective time management allows individuals to accomplish more tasks in less time.\n\nQuestion: What strategy is mentioned as key to maintaining productivity?","optionA":"A. Multitasking all day","optionB":"B. Prioritizing urgent and important tasks","optionC":"C. Delaying difficult decisions","optionD":"D. Working without taking breaks","answerIndex":1,"explanation":"The text notes: 'Prioritizing urgent and important tasks is key...'"},
  {"category":"Verbal Ability","prompt":"Babasahin: Ang pagtutulungan sa komunidad o 'bayanihan' ay isang magandang kulturang Pilipino na dapat panatilihin. Sa gitna ng mga kalamidad, ang bayanihan ang nagbibigay ng pag-asa sa mga nangangailangan.\n\nTanong: Ano ang ibig sabihin ng 'bayanihan' sa teksto?","optionA":"A. Pagtutulungan sa komunidad","optionB":"B. Pakikipag-away sa kapitbahay","optionC":"C. Pag-alis ng bansa","optionD":"D. Pagtatayo ng matayog na gusali","answerIndex":0,"explanation":"Direktang tinukoy ang bayanihan bilang 'pagtutulungan sa komunidad'."},
  {"category":"Verbal Ability","prompt":"Babasahin: Ang bayanihan ay nagbibigay ng pag-asa sa gitna ng kalamidad.\n\nTanong: Ano ang layunin ng may-akda sa talatang ito?","optionA":"A. Ipagmalaki at ipanawagan ang pagpapanatili sa kulturang bayanihan","optionB":"B. Pagtawanan ang mga biktima ng kalamidad","optionC":"C. Baguhin ang mga lumang tradisyon","optionD":"D. Magbenta ng mga produkto sa lalawigan","answerIndex":0,"explanation":"Pinapuri at ipinapanawagan ng may-akda ang pagpapanatili ng bayanihan."},
  {"category":"Verbal Ability","prompt":"Passage: Teamwork in the workplace fosters innovation, as diverse perspectives lead to creative problem-solving. When team members collaborate openly, individual strengths complement each other.\n\nQuestion: What is the main idea of the passage?","optionA":"A. Working alone is always superior.","optionB":"B. Teamwork fosters innovation and creative problem-solving.","optionC":"C. Diversity causes unresolved conflicts.","optionD":"D. Office meetings are a waste of time.","answerIndex":1,"explanation":"The passage emphasizes that teamwork leads to innovation and creative problem-solving."},
  {"category":"Verbal Ability","prompt":"Passage: Teamwork in the workplace fosters innovation...\n\nQuestion: How do diverse perspectives help a team?","optionA":"A. By causing delays in decision-making","optionB":"B. By leading to creative problem-solving","optionC":"C. By increasing administrative costs","optionD":"D. By confusing company executives","answerIndex":1,"explanation":"The passage states: 'diverse perspectives lead to creative problem-solving.'"},
  {"category":"Verbal Ability","prompt":"Babasahin: Ang tamang nutrisyon sa unang 1,000 araw ng buhay ng bata ay napakahalaga para sa kanyang pisikal at mental na pag-unlad. Ang kakulangan sa nutrisyon sa yugtong ito ay maaaring magdulot ng hindi na mababagong pinsala sa kalusugan.\n\nTanong: Bakit mahalaga ang unang 1,000 araw ng bata?","optionA":"A. Dahil dito nakasalalay ang pisikal at mental na pag-unlad","optionB":"B. Dahil dito siya natututong magsalita ng wikang banyaga","optionC":"C. Dahil dito siya pumasok sa paaralan","optionD":"D. Dahil ito ang pinakamasayang panahon","answerIndex":0,"explanation":"Maliwanag na sinabi na mahalaga ito sa pisikal at mental na pag-unlad."},
  {"category":"Verbal Ability","prompt":"Babasahin: Ang tamang nutrisyon sa unang 1,000 araw ay napakahalaga...\n\nTanong: Ano ang maaaring maging bunga ng kakulangan sa nutrisyon sa unang 1,000 araw?","optionA":"A. Mabilis na paglaki","optionB":"B. Hindi na mababagong pinsala sa kalusugan","optionC":"C. Pagtaas ng grado sa paaralan","optionD":"D. Walang anumang epekto","answerIndex":1,"explanation":"Binanggit sa teksto na magdudulot ito ng 'hindi na mababagong pinsala'."},
  {"category":"Verbal Ability","prompt":"Passage: Climate change has led to more frequent and intense weather events, such as typhoons and droughts. Implementing disaster preparedness programs at the local level is vital to protect lives and infrastructure.\n\nQuestion: What conclusion can be drawn from the passage?","optionA":"A. Local communities should invest in proactive disaster readiness to minimize storm damage.","optionB":"B. Weather patterns will return to normal next month.","optionC":"C. Typhoons no longer affect coastal towns.","optionD":"D. Disaster programs are unnecessary.","answerIndex":0,"explanation":"Connecting severe weather risks to local readiness implies investing in proactive preparedness."},
  {"category":"Verbal Ability","prompt":"Passage: Climate change has led to more frequent and intense weather events...\n\nQuestion: What is the main focus of the text?","optionA":"A. The history of typhoon names","optionB":"B. The impact of climate change and the need for local disaster preparedness","optionC":"C. How to build wooden boats","optionD":"D. Tourism in tropical islands","answerIndex":1,"explanation":"The text connects climate change impacts to the necessity of local disaster preparedness."},
  {"category":"Verbal Ability","prompt":"Babasahin: Ang matapat na paglilingkod sa bayan ay nagdudulot ng tiwala at respeto mula sa mga mamamayan. Kapag ang mga pinuno ay malinis ang intensyon, maunlad ang buong komunidad.\n\nTanong: Ano ang magiging bunga ng matapat na paglilingkod ayon sa teksto?","optionA":"A. Tiwala at respeto mula sa mamamayan","optionB":"B. Galit at usap-usapan","optionC":"C. Pagkalugi ng pamahalaan","optionD":"D. Pag-aaway ng mga mamamayan","answerIndex":0,"explanation":"Maliwanag na pahayag na nagdudulot ito ng 'tiwala at respeto'."},
  {"category":"Verbal Ability","prompt":"Babasahin: Kapag ang mga pinuno ay malinis ang intensyon, maunlad ang buong komunidad.\n\nTanong: Ano ang kaisipang ipinahihiwatig ng pahayag?","optionA":"A. Ang magandang pamumuno ay susi sa kaunlaran ng lipunan.","optionB":"B. Hindi kailangan ng pinuno ang maunlad na bayan.","optionC":"C. Ang pera lamang ang nagpapaunlad sa komunidad.","optionD":"D. Walang kaugnayan ang pinuno sa komunidad.","answerIndex":0,"explanation":"Ang ugnayan ng malinis na intensyon ng pinuno sa kaunlaran ay nagpapakita na ang magandang pamumuno ang susi."},
  {"category":"Verbal Ability","prompt":"Passage: Reading comprehension requires not only recognizing words but also understanding context, making inferences, and critical thinking.\n\nQuestion: Which statement is supported by the text?","optionA":"A. Reading is solely about pronouncing words aloud.","optionB":"B. Comprehension involves higher-level thinking skills beyond simple word recognition.","optionC":"C. Inferences are useless in reading.","optionD":"D. Critical thinking hinders reading speed.","answerIndex":1,"explanation":"The text emphasizes context, inferences, and critical thinking beyond basic word recognition."},
  {"category":"Verbal Ability","prompt":"Passage: Reading comprehension requires understanding context and making inferences.\n\nQuestion: What is the primary purpose of this sentence?","optionA":"A. To define the comprehensive nature of reading skills","optionB":"B. To sell a reading textbook","optionC":"C. To complain about difficult exams","optionD":"D. To criticize non-readers","answerIndex":0,"explanation":"The sentence serves to define and clarify what reading comprehension truly entails."},
  {"category":"Verbal Ability","prompt":"Babasahin: Ang pagsunod sa mga panuntunan sa pampublikong lugar ay tanda ng isang disiplinadong mamamayan. Ang maliit na disiplina ng bawat isa ay nagdudulot ng malaking kaayusan sa bansa.\n\nTanong: Ano ang pangunahing mensahe ng talata?","optionA":"A. Ang disiplina sa sarili ay nagdudulot ng pangkalahatang kaayusan sa bansa.","optionB":"B. Ang pampublikong lugar ay para sa ilang tao lamang.","optionC":"C. Mahirap sundin ang mga batas sa lipunan.","optionD":"D. Ang kaayusan ay hindi mahalaga sa bansa.","answerIndex":0,"explanation":"Binibigyang-diin ng talata na ang disiplina ng bawat isa ay nagdudulot ng kaayusan sa bansa."},
  {"category":"Verbal Ability","prompt":"Babasahin: Ang mabilis na pag-unlad ng teknolohiya ay nagdala ng maraming kaginhawaan, tulad ng mabilis na komunikasyon at pagkuha ng impormasyon. Gayunpaman, kinakailangan pa rin ang maingat na paggamit nito upang maiwasan ang maling impormasyon at cybercrime.\n\nTanong: Ano ang pangunahing babala sa teksto?","optionA":"A. Huwag nang gumamit ng teknolohiya kailanman.","optionB":"B. Maging maingat sa paggamit ng teknolohiya upang makaiwas sa maling impormasyon at krimen.","optionC":"C. Mabilis na bumili ng pinakabagong gadyet.","optionD":"D. Ipamahagi ang personal na impormasyon sa internet.","answerIndex":1,"explanation":"Nagbabala ang huling pangungusap tungkol sa maingat na paggamit laban sa cybercrime at maling impormasyon."},
  {"category":"Verbal Ability","prompt":"Passage: Time management is the process of planning and exercising conscious control over time spent on specific activities to increase efficiency, effectiveness, and productivity.\n\nQuestion: According to the passage, what is the ultimate goal of time management?","optionA":"A. To work 24 hours a day without sleeping","optionB":"B. To increase efficiency, effectiveness, and productivity","optionC":"C. To eliminate all leisure activities","optionD":"D. To avoid attending business meetings","answerIndex":1,"explanation":"The passage explicitly states that control over time is exercised to 'increase efficiency, effectiveness, and productivity'."},
  {"category":"Verbal Ability","prompt":"Babasahin: Ang kalikasan ay nagbibigay sa atin ng lahat ng ating pangangailangan sa araw-araw. Kung sisirain natin ang kalikasan, ang tao rin ang magdurusa sa huli sa pamamagitan ng mga sakuna at kagutom.\n\nTanong: Ano ang mahihinuha sa pahayag?","optionA":"A. Ang pangangalaga sa kalikasan ay pangangalaga rin sa sariling kinabukasan ng tao.","optionB":"B. Ang kalikasan ay hindi mauubos kahit sirain.","optionC":"C. Walang epekto ang sakuna sa buhay ng tao.","optionD":"D. Ang tao ay hindi nakadepende sa kalikasan.","answerIndex":0,"explanation":"Dahil ang pagkasira ng kalikasan ay magdudulot ng dusa sa tao, ang pangangalaga rito ay pangangalaga rin sa tao."},
  {"category":"Verbal Ability","prompt":"Passage: Continuous learning throughout one's professional life ensures adaptability in a rapidly changing job market. Employees who invest time in developing new skills are better positioned for career advancement.\n\nQuestion: What is the main idea of the passage?","optionA":"A. Career advancement is purely based on luck.","optionB":"B. Continuous learning and skill development enhance career adaptability and growth.","optionC":"C. Formal education ends permanently upon graduating high school.","optionD":"D. Changing jobs frequently is required for promotion.","answerIndex":1,"explanation":"The passage emphasizes that continuous learning ensures adaptability and positions employees for advancement."},
  {"category":"Verbal Ability","prompt":"Babasahin: Ang disiplina sa paggastos at ang pag-iipon ng bahagi ng kita ay mahalagang hakbang tungo sa pinansyal na kalayaan. Ang taong marunong mag-ipon ay laging may maaasahan sa oras ng pangangailangan.\n\nTanong: Ano ang pangunahing payo ng talata?","optionA":"A. Gastusin agad ang buong kita kapag natanggap.","optionB":"B. Magkaroon ng disiplina sa paggastos at mag-ipon para sa hinaharap.","optionC":"C. Mangutang para makabili ng mga luho.","optionD":"D. Huwag nang magtrabaho.","answerIndex":1,"explanation":"Ipinapayo ng talata ang pagkakaroon ng disiplina sa paggastos at pag-iipon para sa hinaharap."}
];

const batches = [
  { name: 'verbal_batch1_vocabulary.csv', data: batch1 },
  { name: 'verbal_batch2_grammar.csv', data: batch2 },
  { name: 'verbal_batch3_sentence_skills.csv', data: batch3 },
  { name: 'verbal_batch4_reading_skills.csv', data: batch4 }
];

function escapeCsvField(field) {
  if (field === null || field === undefined) return '""';
  const str = String(field).replace(/"/g, '""');
  return `"${str}"`;
}

const headers = ['category', 'prompt', 'optionA', 'optionB', 'optionC', 'optionD', 'answerIndex', 'explanation'];

for (const batch of batches) {
  const csvRows = [headers.join(',')];
  for (const q of batch.data) {
    const row = headers.map(h => escapeCsvField(q[h]));
    csvRows.push(row.join(','));
  }
  fs.writeFileSync(batch.name, csvRows.join('\n'), 'utf8');
  console.log(`✅ Successfully generated ${batch.name} (${batch.data.length} items)`);
}

console.log('\n🎉 All 4 Verbal Ability CSV batches (200 items total) are generated and ready for upload!');