const { processBatchCompletion } = require('./atomic_batch_manager');

const batch004Data = {
  batchNumber: 4,
  batchId: "VA-RC-BESTTITLE-004",
  category: "Verbal Ability",
  component: "Reading Comprehension",
  subtopic: "Core Reading Skills",
  microSubtopic: "Best title",
  modelName: "Gemini 3.6 Flash",
  questions: [
    {
      "Question": "While central bank digital currencies (CBDCs) are frequently heralded by monetary authorities as the ultimate instrument for financial inclusion, their architectural design introduces profound systemic trade-offs. A two-tier retail CBDC model—where the central bank issues digital legal tender distributed through commercial banks—safeguards consumer deposits and facilitates programmable social welfare disbursements to unbanked demographics. However, macroprudential economists warn that during periods of banking distress, depositors can instantly convert commercial bank deposits into risk-free central bank liabilities via mobile devices with zero friction. This frictionless flight-to-safety could accelerate commercial bank runs from days to seconds, severely impairing commercial credit intermediation and starving small and medium enterprises of working capital. Consequently, monetary authorities must balance inclusion objectives against the destabilizing threat of retail disintermediation.\n\nWhich of the following serves as the most appropriate and comprehensive title for the passage?",
      "Option A": "The Total Obsolescence of Traditional Commercial Banking in the Digital Age",
      "Option B": "Retail Central Bank Digital Currencies: Balancing Financial Inclusion Against Systemic Disintermediation Risks",
      "Option C": "How Mobile Applications Eliminate Bank Runs During Financial Panics",
      "Option D": "The Step-by-Step Technical Architecture of Central Bank Distributed Ledger Systems",
      "Correct Answer": "B",
      "Explanation": "Step-by-Step Solution: The passage explores two core dimensions: (1) The benefits of retail CBDCs for financial inclusion and social welfare, and (2) The structural risk of rapid bank disintermediation and credit contraction during panics. The author concludes that central banks must strike a balance between inclusion goals and disintermediation risks. Option B accurately captures both sides of the central argument without overgeneralizing.\n\nCommon Trap: Selecting sensationalized or one-sided titles (Option A or C) that exaggerate the text's nuanced macroprudential balance.\nExam Tip: A superior title must capture both the primary subject and the author's overarching thesis or central tension.",
      "Elimination A": "Eliminated because it is overly sensationalized and distorted; the text discusses regulatory trade-offs, not the complete extinction of commercial banking.",
      "Elimination B": "Correct. Survives elimination because it captures both the primary promise (financial inclusion) and the central danger (systemic disintermediation) explored throughout the text.",
      "Elimination C": "Eliminated because the text explicitly states mobile conversion accelerates bank runs rather than eliminating them.",
      "Elimination D": "Eliminated because the passage focuses on macroeconomic policy implications rather than technical ledger coding.",
      "Category": "Verbal Ability",
      "Tags": "Verbal Ability | Reading Comprehension | Core Reading Skills | Best title | Very Difficult | Batch 004"
    },
    {
      "Question": "In sovereign debt restructuring, the proliferation of 'vulture funds' and non-cooperative holdout creditors has historically paralyzed international financial stability. When a distressed sovereign nation negotiates a debt workout with the supermajority of its bondholders, holdout hedge funds purchase distressed bonds at secondary-market discounts and pursue aggressive litigation in foreign jurisdictions to demand full face-value repayment, effectively holding up post-restructuring economic recovery. To neutralize this predatory dynamic, international legal bodies developed Collective Action Clauses (CACs) with single-limb aggregation mechanisms. Single-limb CACs allow a qualified supermajority of bondholders across all bond issuances to vote collectively to bind all minority creditors to uniform restructuring terms, extinguishing the holdout strategy. Sovereign debt specialists emphasize that universal adoption of aggregated CACs is critical to restoring predictable, orderly, and rapid resolution to sovereign debt crises.\n\nWhat is the most suitable title for the provided text?",
      "Option A": "The Historical Causes of Sovereign Debt Default in Emerging Markets",
      "Option B": "Collective Action Clauses: Reforming Sovereign Debt Restructuring to Neutralize Holdout Creditor Litigation",
      "Option C": "Strategies for Maximizing Speculative Profits Through Distressed Sovereign Bonds",
      "Option D": "A Comprehensive Critique of Supermajority Voting in Corporate Bankruptcy Proceedings",
      "Correct Answer": "B",
      "Explanation": "Step-by-Step Solution: The passage identifies the problem (holdout creditors paralyzing debt restructuring through litigation) and presents the definitive solution (single-limb aggregated Collective Action Clauses that bind minorities to orderly workouts). Title B encapsulates both the core legal mechanism (CACs) and its fundamental objective (reforming restructuring and stopping holdout lawsuits).\n\nCommon Trap: Selecting Option A, which is far too broad and misses the specific legal mechanism (CACs) analyzed in the text.\nExam Tip: Avoid titles that are overly broad historical surveys when the text focuses on a specific policy mechanism.",
      "Elimination A": "Eliminated because it is overly broad; the passage is not a historical survey of all default causes, but a specific analysis of holdouts and CACs.",
      "Elimination B": "Correct. Survives elimination because it precisely identifies the subject (Collective Action Clauses) and its central purpose (neutralizing holdout litigation in sovereign debt restructuring).",
      "Elimination C": "Eliminated because the text evaluates the predatory nature of holdouts and seeks to disarm them, not provide a guide for profit maximization.",
      "Elimination D": "Eliminated because the text deals with sovereign debt restructuring, not corporate bankruptcy.",
      "Category": "Verbal Ability",
      "Tags": "Verbal Ability | Reading Comprehension | Core Reading Skills | Best title | Very Difficult | Batch 004"
    },
    {
      "Question": "Algorithmic governance in social welfare administration promises unprecedented efficiency in identifying eligible beneficiaries and eliminating fraudulent claims through automated data matching. However, when municipal governments deploy predictive risk-scoring algorithms without human oversight, vulnerable households face systemic marginalization. Automated systems routinely flag low-income families for benefit cancellation due to minor typographical discrepancies in fragmented government databases or historical proxies that correlate with systemic poverty rather than actual fraud. Because automated administrative decisions often operate as impenetrable 'black boxes' devoid of transparent reasoning, affected citizens are denied meaningful procedural due process and avenues for timely appeal. Public law scholars argue that the integration of automated decision-making in welfare administration must be bounded by mandatory explainability audits, algorithmic impact assessments, and non-waivable human-in-the-loop review mechanisms.\n\nWhich of the following titles best captures the central theme and argument of the passage?",
      "Option A": "Eliminating Welfare Fraud Through Unchecked Artificial Intelligence Algorithms",
      "Option B": "Algorithmic Welfare Administration: Efficiency Promises, Due Process Hazards, and Safeguards",
      "Option C": "The Complete Elimination of Human Discretion in Public Social Service Agencies",
      "Option D": "Database Management Techniques for Social Welfare Statistical Analysts",
      "Correct Answer": "B",
      "Explanation": "Step-by-Step Solution: The passage balances the initial promise of algorithmic welfare administration (efficiency/fraud detection) against its severe dangers (erroneous cancellations, lack of due process, black-box decisions) and concludes with necessary governance safeguards (explainability audits, human-in-the-loop). Option B captures this tripartite structure: efficiency promises, due process hazards, and governance safeguards.\n\nCommon Trap: Option A advocates for unchecked AI, which is the exact danger the text critiques.\nExam Tip: Look for titles that reflect the critical or cautionary stance of the author rather than blind technological optimism.",
      "Elimination A": "Eliminated because it is distorted; the passage warns against unchecked AI rather than advocating for it.",
      "Elimination B": "Correct. Survives elimination because it captures the efficiency potential, the due process hazards, and the necessity of administrative safeguards.",
      "Elimination C": "Eliminated because the passage actively argues against the complete removal of human oversight.",
      "Elimination D": "Eliminated because the text is a legal-administrative critique, not a database technical manual.",
      "Category": "Verbal Ability",
      "Tags": "Verbal Ability | Reading Comprehension | Core Reading Skills | Best title | Very Difficult | Batch 004"
    },
    {
      "Question": "The transition toward renewable energy has precipitated a profound geopolitical transformation known as the 'Critical Minerals Nexus.' Whereas the hydrocarbon energy paradigm centered geopolitics on oil-producing cartels and maritime shipping chokepoints, the clean energy economy depends heavily on concentrated supply chains of lithium, cobalt, nickel, and rare earth elements essential for battery storage and electric drivetrains. Mineral processing and refining remain overwhelmingly concentrated within a handful of dominant sovereign actors, exposing importing nations to acute geopolitical vulnerability and export restrictions. Energy strategists emphasize that true national energy security in the 21st century requires developing diversified mineral diplomacy, domestic battery recycling technologies, and alternative battery chemistries that decouple clean energy scaling from volatile critical mineral bottlenecks.\n\nWhich title best reflects the overarching discussion in the passage?",
      "Option A": "The Total Elimination of Geopolitical Conflicts in the Post-Fossil Fuel Era",
      "Option B": "The Critical Minerals Nexus: New Geopolitical Realities and Supply Vulnerabilities in the Clean Energy Transition",
      "Option C": "Chemical Properties and Refining Methods of Lithium and Cobalt",
      "Option D": "A Guide to Commercial Electric Vehicle Battery Manufacturing",
      "Correct Answer": "B",
      "Explanation": "Step-by-Step Solution: The passage discusses how the shift to renewable energy replaces oil geopolitics with critical mineral supply dependencies (lithium, cobalt, rare earths) concentrated in few countries, creating new vulnerabilities, and outlines strategies to mitigate these risks. Option B accurately states the core subject (The Critical Minerals Nexus) and the themes of geopolitical reality and supply vulnerability during the energy transition.\n\nCommon Trap: Believing renewable energy eliminates geopolitical conflict (Option A), when the passage shows it creates new resource dependencies.\nExam Tip: Verify whether the proposed title encompasses the global geopolitical scope of the passage.",
      "Elimination A": "Eliminated because it is contradicted by the text; clean energy introduces new geopolitical vulnerabilities rather than eliminating conflict.",
      "Elimination B": "Correct. Survives elimination because it accurately frames the central thesis: the new geopolitical and supply chain vulnerabilities inherent in the critical minerals clean energy nexus.",
      "Elimination C": "Eliminated because chemical properties are not the focus of this geopolitical policy analysis.",
      "Elimination D": "Eliminated because the passage is an energy security policy text, not a commercial manufacturing guide.",
      "Category": "Verbal Ability",
      "Tags": "Verbal Ability | Reading Comprehension | Core Reading Skills | Best title | Very Difficult | Batch 004"
    },
    {
      "Question": "In clinical medical ethics, the principle of patient autonomy frequently encounters challenging ethical dilemmas in psychiatric decision-making involving patients with fluctuating cognitive capacity. Under the traditional paternalistic model, clinicians routinely overrode patient preferences in the name of beneficence whenever a diagnosis of mental illness was established. Conversely, modern bioethics emphasizes the 'Supported Decision-Making' (SDM) paradigm, which presumes legal and decision-making capacity unless proven otherwise through individualized, decision-specific assessments. SDM establishes a structured framework of trusted advocates, communication aids, and advance psychiatric directives that empower individuals with cognitive impairments to exercise self-determination. Bioethicists conclude that SDM successfully reconciles the clinician's ethical duty of protection with the patient's fundamental human right to bodily and psychological autonomy.\n\nWhat is the most precise and appropriate title for this passage?",
      "Option A": "The Historical Superiority of Medical Paternalism in Modern Hospitals",
      "Option B": "Supported Decision-Making in Psychiatry: Reconciling Beneficence with Patient Autonomy",
      "Option C": "Mandatory Involuntary Commitment Procedures in Emergency Psychiatric Wards",
      "Option D": "Neurological Causes of Cognitive Fluctuations in Clinical Patients",
      "Correct Answer": "B",
      "Explanation": "Step-by-Step Solution: The passage contrasts historical paternalism with the modern Supported Decision-Making (SDM) paradigm in psychiatric ethics, showing how SDM reconciles the clinician's duty of beneficence/protection with patient autonomy and rights. Option B captures both the specific subject (Supported Decision-Making in Psychiatry) and the core ethical synthesis (reconciling beneficence with patient autonomy).\n\nCommon Trap: Selecting Option A, which praises paternalism, when the passage supports the modern autonomy-based SDM model.\nExam Tip: Titles should mirror the ethical resolution reached in the passage's concluding sentence.",
      "Elimination A": "Eliminated because it contradicts the passage, which critiques paternalism and advocates for autonomy.",
      "Elimination B": "Correct. Survives elimination because it precisely reflects the subject matter and the central ethical resolution discussed.",
      "Elimination C": "Eliminated because the text focuses on supported decision-making and advance directives, not emergency involuntary commitments.",
      "Elimination D": "Eliminated because the passage is a bioethics analysis, not a neurological pathophysiology text.",
      "Category": "Verbal Ability",
      "Tags": "Verbal Ability | Reading Comprehension | Core Reading Skills | Best title | Very Difficult | Batch 004"
    },
    {
      "Question": "Urban stormwater management has undergone a paradigm shift from traditional 'Gray Infrastructure' (concrete culverts, underground storm sewers, and hardened river walls) to 'Blue-Green Infrastructure' (constructed wetlands, bioswales, permeable pavements, and urban retention ponds). Traditional gray systems focus exclusively on rapid conveyance—discharging stormwater runoff as quickly as possible into natural water bodies, which frequently overwhelms downstream communities and exacerbates urban heat island effects. In contrast, blue-green infrastructure mimics natural hydrological cycles by capturing, detaining, and infiltrating precipitation at the source. By attenuating peak flood discharge while simultaneously replenishing groundwater, filtering pollutants, and cooling ambient city temperatures, blue-green infrastructure provides a multifunctional, climate-resilient framework for sustainable urban flood mitigation.\n\nWhich title most effectively summarizes the core subject and perspective of the passage?",
      "Option A": "The Engineering Specifications for Concrete Drainage Culverts",
      "Option B": "From Gray to Blue-Green: Transforming Urban Flood Management Through Nature-Based Solutions",
      "Option C": "The Complete Elimination of Tropical Storms in Coastal Metropolises",
      "Option D": "Financial Audits of Municipal Wastewater Treatment Plants",
      "Correct Answer": "B",
      "Explanation": "Step-by-Step Solution: The passage describes the transformation in stormwater management from traditional gray infrastructure (concrete pipes focused on rapid runoff discharge) to blue-green infrastructure (nature-based retention, bioswales, wetlands). Option B captures this transition perfectly: 'From Gray to Blue-Green: Transforming Urban Flood Management Through Nature-Based Solutions.'\n\nCommon Trap: Focusing only on the legacy gray systems (Option A) rather than the evolutionary shift to nature-based solutions.\nExam Tip: Look for dynamic titles (e.g., 'From X to Y') when a passage tracks an overarching policy or technological evolution.",
      "Elimination A": "Eliminated because it is too narrow and misses the entire blue-green focus of the passage.",
      "Elimination B": "Correct. Survives elimination because it accurately captures the central transition from conventional gray systems to nature-based blue-green stormwater solutions.",
      "Elimination C": "Eliminated because infrastructure mitigates flooding, but cannot eliminate tropical storms.",
      "Elimination D": "Eliminated because the passage discusses stormwater and flood mitigation, not wastewater financial audits.",
      "Category": "Verbal Ability",
      "Tags": "Verbal Ability | Reading Comprehension | Core Reading Skills | Best title | Very Difficult | Batch 004"
    },
    {
      "Question": "In cybersecurity governance, organizations are increasingly adopting the 'Zero Trust Architecture' (ZTA) framework to replace legacy perimeter-based security models. Traditional castle-and-moat perimeter models operate on the flawed premise that all entities, devices, and traffic inside the internal enterprise network are inherently trustworthy once they breach the outer firewall. This vulnerability allows cyber attackers who compromise a single internal endpoint to move laterally across enterprise systems undetected. Conversely, Zero Trust operates under the core mantra 'never trust, always verify.' ZTA enforces continuous identity verification, granular least-privilege access controls, micro-segmentation of network assets, and end-to-end cryptographic encryption for every transaction, regardless of user location. Cybersecurity analysts emphasize that ZTA represents a foundational defense against sophisticated advanced persistent threats (APTs) in distributed cloud environments.\n\nWhat is the most suitable title for the passage?",
      "Option A": "The Flaws of Cloud Computing in Corporate Organizations",
      "Option B": "Zero Trust Architecture: Overhauling Enterprise Cybersecurity Through Continuous Verification",
      "Option C": "Why Firewalls Offer Complete Protection Against All Cyber Threats",
      "Option D": "A Guide to Recovering Ransomware Payments for Financial Institutions",
      "Correct Answer": "B",
      "Explanation": "Step-by-Step Solution: The text contrasts legacy perimeter defenses ('castle-and-moat') with the modern Zero Trust Architecture (ZTA), outlining ZTA's philosophy ('never trust, always verify'), structural pillars (micro-segmentation, continuous verification, least privilege), and defense against lateral movement and APTs. Option B encapsulates the core subject and paradigm shift.\n\nCommon Trap: Selecting Option C, which directly contradicts the passage's argument that firewalls are insufficient.\nExam Tip: A great title captures both the named framework and its operative principle (e.g., 'Zero Trust Architecture... Continuous Verification').",
      "Elimination A": "Eliminated because the text presents Zero Trust as a security solution for cloud networks, not a critique of cloud computing.",
      "Elimination B": "Correct. Survives elimination because it states the exact model (Zero Trust Architecture) and its core mechanism (continuous verification in enterprise security).",
      "Elimination C": "Eliminated because it directly contradicts the text, which shows firewalls alone leave internal networks vulnerable to lateral movement.",
      "Elimination D": "Eliminated because ransomware recovery payments are unmentioned.",
      "Category": "Verbal Ability",
      "Tags": "Verbal Ability | Reading Comprehension | Core Reading Skills | Best title | Very Difficult | Batch 004"
    },
    {
      "Question": "The concept of 'Regulatory Sandboxes' has emerged as a premier regulatory innovation in financial technology (fintech) supervision. Traditional financial regulation requires strict upfront licensing and capital compliance before an enterprise can launch a product, creating high barriers to entry that stifle innovative fintech startups. A regulatory sandbox provides a controlled, time-bound testing environment where startups can test innovative financial products, services, or delivery channels with real consumers under tailored, relaxed regulatory requirements and active regulatory oversight. This mechanism allows regulatory authorities like central banks to observe novel technologies (such as blockchain lending or AI credit scoring) in real time, identify emerging consumer risks, and update statutory frameworks without crushing market innovation. Financial policy scholars view regulatory sandboxes as an essential tool to foster competitive financial innovation while maintaining systemic consumer protection.\n\nWhich title best captures the primary focus and value proposition discussed in the passage?",
      "Option A": "How Financial Startups Evade Central Bank Regulations Legally",
      "Option B": "Regulatory Sandboxes: Balancing Fintech Innovation with Prudent Market Supervision",
      "Option C": "The Complete Abolition of Capital Adequacy Requirements for Commercial Banks",
      "Option D": "A Technical Manual on Developing Decentralized Blockchain Protocols",
      "Correct Answer": "B",
      "Explanation": "Step-by-Step Solution: The text analyzes Regulatory Sandboxes as a supervisory mechanism that allows fintech startups to test innovations in a controlled environment while enabling central banks to supervise risks and update regulations without stifling growth. Option B captures the subject (Regulatory Sandboxes) and the balance between fintech innovation and market supervision.\n\nCommon Trap: Choosing sensationalized negative titles (Option A) that misunderstand the legal intent of sandbox regimes.\nExam Tip: In governance and regulatory passages, look for balanced phrasing like 'Balancing Innovation with Supervision'.",
      "Elimination A": "Eliminated because sandboxes are official, collaborative supervisory programs, not schemes to evade law.",
      "Elimination B": "Correct. Survives elimination because it highlights both key aspects: fintech innovation and prudent market supervision.",
      "Elimination C": "Eliminated because capital requirements for commercial banks are not abolished.",
      "Elimination D": "Eliminated because the passage is a financial regulation analysis, not a technical coding manual.",
      "Category": "Verbal Ability",
      "Tags": "Verbal Ability | Reading Comprehension | Core Reading Skills | Best title | Very Difficult | Batch 004"
    },
    {
      "Question": "In public agricultural policy, the debate between 'Food Security' and 'Food Sovereignty' reflects fundamentally divergent developmental philosophies. Food Security, as traditionally defined by global institutions, focuses on the availability, accessibility, and affordability of adequate food supplies for all people, irrespective of whether the food is produced domestically or imported via globalized agro-industrial trade networks. In contrast, the Food Sovereignty movement argues that true resilience requires communities and nations to exercise democratic control over their own food and agricultural systems. Food sovereignty prioritizes agroecological farming methods, the defense of smallholder agrarian land rights, biodiversity preservation, and local food production over corporate-dominated global commodity supply chains. Agrarian sociologists highlight that while Food Security addresses nutritional access, Food Sovereignty tackles the underlying structural power asymmetries governing global food distribution.\n\nWhich of the following serves as the most accurate and insightful title for the text?",
      "Option A": "Food Security vs. Food Sovereignty: Contrasting Commodity Availability with Agrarian Self-Determination",
      "Option B": "Why Developing Countries Must Rely Exclusively on Multinational Food Imports",
      "Option C": "Agricultural Methods for Maximizing Chemical Fertilizer Yields",
      "Option D": "The Complete Eradication of Global Hunger Through Corporate Trade Agreements",
      "Correct Answer": "A",
      "Explanation": "Step-by-Step Solution: The passage contrasts two major paradigms: Food Security (ensuring food availability and affordability through trade and markets) vs. Food Sovereignty (community self-determination, agrarian rights, agroecology, democratic control of food systems). Option A captures both concepts and their respective philosophical cores ('Commodity Availability' vs. 'Agrarian Self-Determination').\n\nCommon Trap: Picking an option that endorses corporate dependency (Option B or D), which the text explicitly critiques.\nExam Tip: When a passage juxtaposes two concepts, the best title names both and highlights their fundamental contrast.",
      "Elimination A": "Correct. Survives elimination because it precisely frames the comparative tension between market/commodity access (Food Security) and systemic self-determination (Food Sovereignty).",
      "Elimination B": "Eliminated because it contradicts the Food Sovereignty perspective presented in the text.",
      "Elimination C": "Eliminated because chemical fertilizers are not the focus of this developmental policy passage.",
      "Elimination D": "Eliminated because it is unsubstantiated and contrary to the critique of corporate supply chains in the text.",
      "Category": "Verbal Ability",
      "Tags": "Verbal Ability | Reading Comprehension | Core Reading Skills | Best title | Very Difficult | Batch 004"
    },
    {
      "Question": "The organizational theory of 'Ambidextrous Leadership' addresses the fundamental tension between 'Exploitation' and 'Exploration' in public sector innovation. Exploitative activities involve optimizing existing administrative processes, enforcing compliance, improving operational efficiency, and reducing variance in routine public service delivery. Exploratory activities, by contrast, involve experimental risk-taking, prototyping novel public services, challenging established standard operating procedures, and embracing calculated failures to discover breakthrough solutions. Administrative scholars emphasize that successful public sector executives must cultivate ambidexterity—the cognitive and structural agility to simultaneously maintain operational discipline in core baseline operations while establishing protected organizational incubators for creative experimentation.\n\nWhat is the most fitting title for the passage?",
      "Option A": "The Total Abandonment of Standard Operating Procedures in Government Agencies",
      "Option B": "Ambidextrous Leadership: Harmonizing Operational Efficiency with Public Sector Innovation",
      "Option C": "Techniques for Eliminating All Administrative Risks in Public Service Delivery",
      "Option D": "A Historical Survey of Civil Service Disciplinary Tribunals",
      "Correct Answer": "B",
      "Explanation": "Step-by-Step Solution: The passage defines Ambidextrous Leadership as the ability of public sector leaders to balance two competing organizational needs: Exploitation (refining existing processes, efficiency, compliance) and Exploration (experimentation, innovation, novel public services). Option B captures this dual balance: 'Ambidextrous Leadership: Harmonizing Operational Efficiency with Public Sector Innovation.'\n\nCommon Trap: Selecting extreme options (Option A) that misrepresent the dual-balance nature of ambidexterity.\nExam Tip: Look for terms like 'Harmonizing', 'Balancing', or 'Integrating' when titling passages about organizational ambidexterity.",
      "Elimination A": "Eliminated because the text emphasizes that core operations and standard procedures must still be maintained.",
      "Elimination B": "Correct. Survives elimination because it captures the concept of Ambidextrous Leadership and the synthesis of efficiency and innovation.",
      "Elimination C": "Eliminated because exploration requires embracing calculated risks rather than eliminating all risks.",
      "Elimination D": "Eliminated because disciplinary tribunals are unmentioned.",
      "Category": "Verbal Ability",
      "Tags": "Verbal Ability | Reading Comprehension | Core Reading Skills | Best title | Very Difficult | Batch 004"
    }
  ]
};

const result = processBatchCompletion(batch004Data);
console.log(JSON.stringify(result, null, 2));
